### ISSUE TITLE
Part of a done button title is displayed off the screen

### ISSUE THREAD

**Issue by Mattijah** [mikaoj/BSImagePicker#106]
Part of a done button title is displayed off the screen.

BSImagePicker `2.4.0`
iOS 10
iPhone 7

![simulator screenpng](https://cloud.githubusercontent.com/assets/3887042/19624461/c2326810-98ee-11e6-80b3-02d512229eb2.png)

**Comment by Mattijah** [comment]
I just noticed that the bug was fixed here https://github.com/mikaoj/BSImagePicker/commit/c7ffe67ba82eb29e351028a907531215e64beeb7. Why does the `2.4.0` release says that it includes `iOS 10 bugfixes`?

**Comment by mikaoj** [comment]
Because it fixed som crashes that could occur on iOS 10.
I'm closing this since it's already fixed...reopen if you feel otherwise 😊

**Comment by fumitoito** [comment]
*Just a reporting*

This issue was fixed at `2.5.0` release. NOT `2.4.0`.
