### ISSUE TITLE
Can't satisfy dependency on UIImageViewModeScaleAspect (v 2.5.0)

### ISSUE THREAD

**Issue by nikans** [mikaoj/BSImagePicker#108]
```
[!] Unable to satisfy the following requirements:

- `UIImageViewModeScaleAspect (~> 1.5.0)` required by `BSImagePicker (2.5.0)`
```

Shouldn't it use `UIImageViewModeScaleAspect` v. 2.0?

**Comment by nikans** [comment]
Looks like you should require `UIImageViewModeScaleAspect` 1.5, not 1.5.0. Turns out, it makes difference )

**Comment by nikans** [comment]
I've created a fork w/ a tmp fix https://github.com/nikans/BSImagePicker

**Comment by mikaoj** [comment]
Great! Pull requests are welcome 🙂

**Comment by mikaoj** [comment]
Which version of cocoapods where you using? 1.1.0 managed to resolve 1.5.0 to 1.5
I've pushed 2.5.1 which has 1.5 in the podspec, hope that works better for you.
