### ISSUE TITLE
Invalid update: invalid number of items in section 1.

### ISSUE THREAD

**Issue by IldarMurzenkov** [mikaoj/BSImagePicker#113]
Hello,
 
I use pod version 2.5.1; ios version 10.0.
When i am trying to save photo from my app PHPhotoLibraryChangeObserver is executed succesfuly, but when i try to save another photo in a second time i have 'NSInternalInconsistencyException' in the method DispatchQueue.main.async:
`  if let inserted = photosChanges.insertedIndexes {
                        collectionView.insertItems(at: inserted.bs_indexPathsForSection(1))
     }`
Detailed exception text: Invalid update: invalid number of items in section 1.  The number of items contained in an existing section after the update (1543) must be equal to the number of items contained in that section before the update (1543), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'

Could you please answer me, how i should fix this issue?

Thanks,
Ildar

**Comment by IldarMurzenkov** [comment]
Calling `collectionView.performBatchUpdates(nil, completion: nil)` method after `collectionView.reloadData()` has solved the problem. But i think this is not correct method. Could you please write what do you think about this? Maybe you can provide more suitable solution for this issue?

**Comment by sobanhameed** [comment]
We seem to have hit this issue as well.  We will try out the above recommendation.
