### ISSUE TITLE
defaultSelection not available

### ISSUE THREAD

**Issue by rujoota** [mikaoj/BSImagePicker#125]
Hi,

I recently migrated to swift 3.0 with xCode 8.2.
I am using "BSImagePicker", "~> 2.4" pod.
I am not able to use defaultSelection anymore. It keeps throwing compile time error that its private.
I know that it has been made public because of previous issues but somehow its not available neither it appears in xCode intellisense. Can you check the issue?

**Comment by RamandeepGosal** [comment]
Yes they have been made private in both the files 
1. PhotosViewController
2. BSImagePickerViewController

I was also using the same variable in swift 2.3 to check the previously chosen images form the photos but with the update for swift 3 they have been made private and its difficult to pre-select the images. 
Hope to here from the them for the alternative sooner.
