### ISSUE TITLE
Cannot preview some images in camera roll stored in iCloud Photo Library

### ISSUE THREAD

**Issue by Marcoc88** [mikaoj/BSImagePicker#126]
I have only bee able to re-create this on devices that store photos in iCloud. If I scroll far down in the image selector then long press on an image to preview it, the image does not show and instead I get a white image. In Xcode I get the message "ERROR, UIImageView <UIImageViewModeScaleAspect: 0x145db4910; frame = (0 0; 375 667); clipsToBounds = YES; layer = <CALayer: 0x174220680>> don't have UIImage".  

It seems like not all images are getting downloaded from iCloud and therefore there is no image actually available, just the thumbnail. If I select the thumbnail and try to do something with the PHAsset I get the error message "Failed to load image data for asset <PHAsset: ..... (2448x3264), creationDate=2016-12-06 01:34:55 +0000, location=1, hidden=0, favorite=0  with format 9999"

**Comment by Marcoc88** [comment]
I found this can be fixed by calling isNetworkAccessAllowed on the PHContentEditingInputRequestOptions

**Comment by AlexVincent525** [comment]
Hi, could you plz tell me where the PHContentEditingInputRequestOptions is? Thx a lot.
