### ISSUE TITLE
errors inside BSImagePicker-Swift.h

### ISSUE THREAD

**Issue by lukejones1** [mikaoj/BSImagePicker#128]
<img width="1037" alt="screen shot 2017-03-09 at 08 34 15" src="https://cloud.githubusercontent.com/assets/18525477/23742108/8816ce48-04a3-11e7-9aa4-bb8a47286f03.png">

Not sure whats going on.

Also, whats with the rick astley video lol

**Comment by karimlanguedoc** [comment]
I ran into this exact issue. I'm pretty sure it's because you're using an outdated version of Xcode. In my case, I was using 8.0 instead of the latest version. Update Xcode, clean and build. It should work.

**Comment by lukejones1** [comment]
Work's perfectly now, thanks
