### ISSUE TITLE
how to fetch Video file?

### ISSUE THREAD

**Issue by sidshah13** [mikaoj/BSImagePicker#134]
I can't fetch video file using bsimagepicker

**Comment by midhetfatema94** [comment]
This is an Image picker, so you can't fetch video files, but if you want to fetch other images, you can click the top middle section and choose the album you want to go into.

**Comment by sidshah13** [comment]
that think i know but i want to fetch video too.

**Comment by justrktiwari** [comment]
> that think i know but i want to fetch video too.

have you got the solution?
