### ISSUE TITLE
keepSelection property

### ISSUE THREAD

**Issue by ritika1159** [mikaoj/BSImagePicker#137]
hi,

I have read in some article that this library provides keepSelection property.

keepSelection 

@property (nonatomic, assign) BOOL keepSelection
Discussion

Set this to yes to keep selection after close

But I am not able to find this. Please let me know if this property exists.

I would highly appreciate if you could do this asap.

Thanks !!

Regards
Ritika

**Comment by nodirashidov** [comment]
Hello, could you find the answer to your question? I need help with this as well

**Comment by eldarkk** [comment]
Seriously guys, is it impossible to reset selection after pressing Done button ??

**Comment by mikaoj** [comment]
"Reseting" selections is easy, just create a new BSImagePicker instance.
Instead of doing something like this:
```
class ViewController: UIViewController {
  let imagePicker = BSImagePicker()

  func presentPicker() {
    present(imagePicker)
  }
}
```

Do this:
```
class ViewController: UIViewController {
  func presentPicker() {
    let imagePicker = BSImagePicker()
    present(imagePicker)
  }
}
```
