### ISSUE TITLE
IB Designables: Failed to update auto layout status

### ISSUE THREAD

**Issue by tdimeco** [mikaoj/BSImagePicker#141]
Hi!

I have a build time error `IB Designables: Failed to update auto layout status` that appears inside the error panel each time I compile. This error does not abort the compilation, but is still here. Do you know how to fix it?

Thanks!

Thomas

Library: 2.6.0
Xcode: 8.3.2
Swift: 3.1
macOS: 10.12.4
iOS: 9.0+

<img width="342" alt="error" src="https://cloud.githubusercontent.com/assets/3112087/25804235/fd32c1b0-33fa-11e7-9b62-04f001809a8b.png">

**Comment by AlanValencia** [comment]
I have the same issue.
Library: 2.5.0
Xcode: 8.0, 8.1, 8.2.1
