### ISSUE TITLE
Swift 4 Migration Issue

### ISSUE THREAD

**Issue by corbinhudson** [mikaoj/BSImagePicker#150]
2 errors occur after migrating to swift 4.
![screen shot 2017-09-21 at 3 09 36 pm](https://user-images.githubusercontent.com/26608161/30713965-1a65b82e-9edf-11e7-9c25-034ef3ee051d.png)

**First error** 
Initializer for conditional binding must have Optional type, not 'AVCaptureVideoPreviewLayer'
![screen shot 2017-09-21 at 3 13 14 pm](https://user-images.githubusercontent.com/26608161/30714055-6d1b6ad2-9edf-11e7-87ca-0ea25ea7d31a.png)

**Second Error**
Cannot convert value of type '[String : AnyObject]' to expected argument type '[NSAttributedStringKey : Any]?'
![screen shot 2017-09-21 at 3 11 59 pm](https://user-images.githubusercontent.com/26608161/30714025-55ab4822-9edf-11e7-976f-4568a24d7de6.png)

**Comment by jjpatel1996** [comment]
I'm also facing same issue.

**Comment by corbinhudson** [comment]
Resolved with Swift 4 Update
