### ISSUE TITLE
Cant open albums list

### ISSUE THREAD

**Issue by egorbzk** [mikaoj/BSImagePicker#152]
On iOS 11 can't open albums list

**Comment by mikaoj** [comment]
This is a known issue in iOS 11, hopefully they'll fix it soon.
But I've released 2.7.1 with a workaround.

**Comment by egorbzk** [comment]
I fix it by change in PhotosViewController.swift on line 121 navigationItem.titleView = albumTitleView

**Comment by mikaoj** [comment]
Or you could update to 2.7.1 which puts the button directly in the title view :)
