### ISSUE TITLE
Swift 4 Compatibility Issues 

### ISSUE THREAD

**Issue by Daniyal261** [mikaoj/BSImagePicker#154]
Pod is not converted to Swift 4 properly yet. Looking forward to it. I have integrated this pob previously in my project now i am stuck with it.
<img width="1277" alt="screen shot 2017-10-04 at 12 47 11 pm" src="https://user-images.githubusercontent.com/7877899/31164902-64171530-a902-11e7-9adf-2a566699ae44.png">

I hope you guys convert it to swift 4 and compatible to Xcode 9 soon

Installing BSGridCollectionViewLayout 1.2.0 (was 1.2.0-swift23)
Installing BSImagePicker 2.7.1

I have updated my pods even then i am facing the issue.

Issue 150 was also about the same issue and was closed but issue is not solved yet

**Comment by mikaoj** [comment]
This should indeed be solved by now, but yes as you have to change swift language version in the project file.
