### ISSUE TITLE
Dependency "BSImagePicker" has no shared framework schemes

### ISSUE THREAD

**Issue by aksenkin** [mikaoj/BSImagePicker#155]
Hello, I was trying to build your BSImagePicker using Carthage v 0.26.0 and v 0.26.2
CLT from Xcode 9.0 (9A235), Swift 4

I got the following error:
>carthage update --platform ios
*** Fetching BSImagePicker
*** Fetching BSGridCollectionViewLayout
*** Fetching UIImageViewModeScaleAspect
*** Checking out UIImageViewModeScaleAspect at "1.5"
*** Checking out BSImagePicker at "2.7.1"
*** Checking out BSGridCollectionViewLayout at "1.2.0"
*** xcodebuild output can be found in /var/folders/9p/wqy_tmzx635bv1lnltq8jkh00000gn/T/carthage-xcodebuild.si2ImJ.log
*** Building scheme "BSGridCollectionViewLayout" in BSGridCollectionViewLayout.xcworkspace
*** Building scheme "UIImageViewModeScaleAspect" in UIImageViewModeScaleAspect.xcodeproj
*** Skipped building BSImagePicker due to the error:
Dependency "BSImagePicker" has no shared framework schemes for any of the platforms: iOS

>carthage update
*** Fetching BSImagePicker
*** Fetching BSGridCollectionViewLayout
*** Fetching UIImageViewModeScaleAspect
*** Checking out UIImageViewModeScaleAspect at "1.5"
*** Checking out BSImagePicker at "2.7.1"
*** Checking out BSGridCollectionViewLayout at "1.2.0"
*** xcodebuild output can be found in /var/folders/9p/wqy_tmzx635bv1lnltq8jkh00000gn/T/carthage-xcodebuild.tNTA7c.log
*** Building scheme "BSGridCollectionViewLayout" in BSGridCollectionViewLayout.xcworkspace
*** Building scheme "UIImageViewModeScaleAspect" in UIImageViewModeScaleAspect.xcodeproj
*** Skipped building BSImagePicker due to the error:
Dependency "BSImagePicker" has no shared framework schemes

My Cartfile looks like
~~~~
# BSImage
github "mikaoj/BSImagePicker" ~> 2.5.1
~~~~
I've added shared schema but even in this case I got error for BSImagePicker FW.

**Comment by mikaoj** [comment]
Pushed 2.8.1 which should work with carthage
