### ISSUE TITLE
Album Title View button tint color

### ISSUE THREAD

**Issue by michalcickan** [mikaoj/BSImagePicker#158]
Hello,

is it necessary to create album title view button with titleColor? 

` @objc var albumTitleView: UIButton = {
        let btn =  UIButton(frame: .zero)
        btn.setTitleColor(btn.tintColor, for: .normal)
        return btn
    }()`

It cancel appearance. When you write 

`UIButton.appearance(whenContainedInInstancesOf: [UINavigationBar.self]).tintColor = .white`

 then it is ignored because of this settings. It is not in navbar yet, so tint color is setted by global UIButton tint color. If I comment line setTitleColor, everything works as should.

**Comment by bovillaios** [comment]
Hi,
How can we change the title color? I am not able to change through the properties of BSImagePickerViewController's object.

Thanks in advance,
Ramgopal
