### ISSUE TITLE
some picture would disapper when i long press in 'BSImagePickerViewController'

### ISSUE THREAD

**Issue by wanqingrongruo** [mikaoj/BSImagePicker#161]
when I `bs_presentImagePickerController`, I want to preview a picture by long press, then some accidents happend. There are some pictures show in a flash lefting a space, sure also some picture show normally. I don't know what caused this situation

![normal situation](https://user-images.githubusercontent.com/11460183/32766960-45f79d8a-c94c-11e7-9790-84678f49ef84.PNG)
![abnormal situation](https://user-images.githubusercontent.com/11460183/32767027-96f6a33e-c94c-11e7-8bcb-f14f7f8eb1a3.PNG)

**Comment by wanqingrongruo** [comment]
I think... the path: .../PhotosViewController.swift, row 203
```
let options = PHImageRequestOptions()
                options.isSynchronous = true
                options.isNetworkAccessAllowed = true
```
the `isNetworkAccessAllowed` should be setted `true`. Sometimes the picture may be icloud , if we make true to show, we should allow the iphone to download the photo from iCloud

**Comment by luckycherry** [comment]
怎么解决的 我长按图片预览也是空白

**Comment by luckycherry** [comment]
Where to add the code

**Comment by luckycherry** [comment]
i think so
