### ISSUE TITLE
Remove selected images when cancel has been pressed

### ISSUE THREAD

**Issue by DhruvTekchandani** [mikaoj/BSImagePicker#165]
Hey, im not sure if this is something I cant do but I feel I havent been able to firgure it out yet.

Lets say for example the user has selected images and then decides to cancel it. 
How can I remove those selected images? Cause at the momemt if I press the camera button 
again those images are still selected.

Thank you for your time.
Dhruv Tekchandani.

**Comment by khushDesai** [comment]
Hey @DhruvTekchandani , Have you solved this issue? I am facing same issue.
Please Help,
Thanks .!

**Comment by Klavar** [comment]
Solved this..

put assigning the picker to a variable in the action such as function or button press rather than in the above view did load

like this....
func addImages() {
		let vc = BSImagePickerViewController()

This sets the imagePicker controller fresh each time you load it up.
