### ISSUE TITLE
Random crash on Iphone 6s

### ISSUE THREAD

**Issue by deepti82** [mikaoj/BSImagePicker#166]
Hi,
here I attached my crash log file . I am getting this issue for one of app user .Can you help me to come out from this issue.
Thanks

[crash.txt](https://github.com/mikaoj/BSImagePicker/files/1591302/crash.txt)

**Comment by garyfoster** [comment]
We're seeing this on a variety of devices 7, 5, 6s, X, etc

**Comment by deepti82** [comment]
ya this issue coming on Ios 10.2.1  and the device which has low RAM.so if You are  using multiple selection of  photo more than 10 than the crash frequency increased.
