### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by mabdullahsaeed** [mikaoj/BSImagePicker#173]
I just updated to XCode 9.2. I tried using Swift version 3.2  and version 4.0 under Swift Compiler-Language option in Build settings but I am getting a lot of errors (shown in picture) when I try to build the app. I am stuck on building my app.
![screen shot 2018-02-26 at 1 30 11 pm](https://user-images.githubusercontent.com/16466926/36650923-1493f9a0-1afa-11e8-8605-a5ed4662a4ee.png)

**Comment by mikaoj** [comment]
And you have set Swift 4 on the BSImagePicker target in the Pods project and not on your App target in the app project?

**Comment by mabdullahsaeed** [comment]
Yes, I have set the target to Swift 4 in both locations

**Comment by mikaoj** [comment]
And which version of BSImagePicker are you using?

**Comment by Biyao-NoteVault** [comment]
Hi mikaoj, I have the same issue here. I set swift 3.3 for both pods and my project, and the version I'm using is 2.7.1, my xcode version is 9.3. Could you please help me with this?

**Comment by mikaoj** [comment]
Set it to Swift 4?

**Comment by stellasu** [comment]
It works thank you!

**Comment by Biyao-NoteVault** [comment]
Set to Swift 4 and it worked, thank you!
