### ISSUE TITLE
Please fix this warning 'flatMap is deprecated Please use compactMap(_:)' in swift 4.1

### ISSUE THREAD

**Issue by jjpatel1996** [mikaoj/BSImagePicker#175]
I'm getting this warning from BSImagePicker and BsGridCollectionLayout that 'flatMap is deprecated Please use compactMap(_:)'

**Comment by NoahCardoza** [comment]
This still seems to be an issue. When I build my app I get `Value of type '[UICollectionViewLayoutAttributes?]' has no member 'compactMap'` I'm fairly new to Swift in general, is this something on my end?
