### ISSUE TITLE
It's useless to set doneButton.tintColor

### ISSUE THREAD

**Issue by ChokShen** [mikaoj/BSImagePicker#177]
I downloaded your demo to test 'showCustomImagePicker',but I found that setting doneButton.tintColor is not useful at all.

**Comment by khushDesai** [comment]
@ChokShen  If you want to change tint color of Done button then go to the **PhotosViewController**
and change color in **updateDoneButton**

![screen shot 2018-05-29 at 5 35 34 pm](https://user-images.githubusercontent.com/29880773/40657790-c3f52d6a-6366-11e8-9630-3cfee9acccbb.png)
