### ISSUE TITLE
image not getting in orignal size 

### ISSUE THREAD

**Issue by ioshitendra** [mikaoj/BSImagePicker#179]
Hello i am using BSImagePiker Library in my project i am successful implement and select Multiple  image  and retrive but when i retrive image in PHAsset it is not getting orignal size it is compress i am also do code for PHImageManagerMaximumSize  but  image is show blur in image viewer

**Comment by swiftty** [comment]
Have you tried setting the PHImageRequestOptions'resize mode to exact? Like:

```
let manager = PHImageManager.default()
let option = PHImageRequestOptions()
option.resizeMode = .exact
```
and then set: 

 ```
manager.requestImage(for: asset, targetSize: PHImageManagerMaximumSize, contentMode: .aspectFill, options: option, resultHandler: {(result, info) -> Void in
          // do your stuff 
})
```

I'm doing it that way and its working for me

**Comment by bhuvvii** [comment]
Thank you for the update .Now my image is having original size .I have changed my targetSize so i m getting original image
