### ISSUE TITLE
Selection number color

### ISSUE THREAD

**Issue by namnguyens** [mikaoj/BSImagePicker#18]
It seems like the background color for selection numbers are the same as navigation bar title.
I would like to have the background color to be the same as my navigation bar.

If I set the navigation title color to white, it changes the selection background color to white, but the selection title color is also white.

**Comment by mikaoj** [comment]
This issue missed the 1.1.0 window, but I'm getting there...hoping to have it ready for 1.2.0

**Comment by mikaoj** [comment]
Soo...1.1.0 yesterday and 1.2.0 today which allows you to tweak with selection colors/fonts/etc :)
(1.1.0 exposed the views in the navigation bar for you to tweak)
