### ISSUE TITLE
All images are blurred

### ISSUE THREAD

**Issue by PhilippRosengart** [mikaoj/BSImagePicker#180]
I tried to use the BSImagePicker for multiple Image selection.
But all images are blurred. The ImagePickerController is shown and there already all images are blurred, and after selection they stay blurred.
I'm using Xcode 9.4 with iOS 11.4

**Comment by bhuvvii** [comment]
I too tried BsImagePicker ,Mine is also showing Like Blurred .

**Comment by mikaoj** [comment]
Hmm, with a vanilla image picker or have you made any settings / custom fetch results / etc?
