### ISSUE TITLE
How to make controller close after picking just a single image

### ISSUE THREAD

**Issue by ntkon** [mikaoj/BSImagePicker#181]
Hi, Is it possible to set something so that when an image is picked the controller closes, like a single image picker. If I set the `maxNumberOfSelections` to 1 you still have to press the Done button to exit the picker. I wanted to just get a single image from the first tap on a picture.

Thanks.

PS  Great library much appreciated.

**Comment by mikaoj** [comment]
Sure, in the selection closure you can simply dismiss the image picker.

**Comment by ntkon** [comment]
Thanks for that @mikaoj and sorry for the late response (been on holidays).
