### ISSUE TITLE
Showing already selected photos when BSImagePicker is shown multiple times?

### ISSUE THREAD

**Issue by ghost** [mikaoj/BSImagePicker#183]
Is there a way to show already selected assets when the `BSImagePickerViewController` is presented multiple times and change the "Done" button according to the number of already (previously) selected  assets? Ie. lets say we set the `maxNumberOfSelections` to 5, the user selected 3 photos, but then decided to add 2 more. 

As of now (or from what I see), every time the BSImagePickerController is presented, it doesn't show previously selected photos (which could be a bit confusing for the user, especially if you set the `maxNumberOfSelections` to 10 for example)

**Comment by Omeesh** [comment]
Don't take a global variable of BSImagePickerViewController() type.
Instead create a new variable of image picker each time you add image

func addImages(){
        let imgPicker = BSImagePickerViewController()
        
        imgPicker.maxNumberOfSelections = 10
        imgPicker.settings.takePhotos = true
        imgPicker.selectionFillColor = appColor
        
        bs_presentImagePickerController(imgPicker, animated: true,
                                        select: { (asset: PHAsset) -> Void in
                                            // User selected an asset.
        }, deselect: { (asset: PHAsset) -> Void in
            // User deselected an assets.
        }, cancel: { (assets: [PHAsset]) -> Void in
        }, finish: { (assets: [PHAsset]) -> Void in
            for asset in assets{
                let img = self.getAssetThumbnail(asset: asset)
                    img.accessibilityHint = "exist"
                self.imagesArray.append(img)
            }
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
            
        }, completion: nil)
    }

**Comment by Klavar** [comment]
Exelent this helped me out alot, i was wondering why when I started the image picker it still had old images selected before already selected, seing the picker in the action stoped that.

put here:
func addImages() {
		let vc = BSImagePickerViewController()

instead of view did load...
