### ISSUE TITLE
Getting error with Xcode 10

### ISSUE THREAD

**Issue by Sh1d0w** [mikaoj/BSImagePicker#185]
**Describe the bug**
error: module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/user/Projects/example/build/ios/Debug-iphonesimulator/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/x86_64.swiftmodule

**Comment by mikaoj** [comment]
I'll get an Swift 4.2 version ready. In the meantime build it in Swift 4.1/4.0 compiler mode (whichever you can choose from in Xcode 10).

**Comment by Sh1d0w** [comment]
@mikaoj Thanks for your answer. I have selected Swift 4 in the build configuration, but it still fails with the same error.

![error](https://i.imgur.com/863NRtz.png)

**Comment by Sh1d0w** [comment]
Never mind, I guess you mean to compile your library not the project itself, as it currently is using the prebuilt binary. Will wait for you to release the 4.2 support, no rush.

Thanks.

**Comment by mikaoj** [comment]
Give 2.8.2 a try and let me know if it works out for you :)

**Comment by Sh1d0w** [comment]
@mikaoj Worked like a charm! Thank you very much!
