### ISSUE TITLE
UIBarButtonItem Title Issue

### ISSUE THREAD

**Issue by mrduyu** [mikaoj/BSImagePicker#189]
Hi,
I try to use imagepicker component as explained. I successfully use it but there is something wrong I cannot figure it out.
I try to change title of UIBarButtonItems.
I could change title of **Cancel** button to 'İptal' but I couldn't change title of **Done** button. Could you please help me how can I progress about this issue.
![issue](https://user-images.githubusercontent.com/40163745/46344879-4bb80c80-c64b-11e8-9417-62cdbbb6289c.jpg)

And this is my code block:
        bsVC.doneButton = **UIBarButtonItem(title: "Tamam" , style: UIBarButtonItemStyle.plain, target: nil, action: nil)**
        bsVC.cancelButton = **UIBarButtonItem(title: "İptal", style: UIBarButtonItemStyle.plain, target: nil, action: nil)**
        bsVC.albumButton.isHidden = true
Thank you.
Emre.

**Comment by mikaoj** [comment]
In your project you should have a file called Localizable.strings.
Add the following line in it:
"Done" = "Tamam";

**Comment by mrduyu** [comment]
Thanks! It worked.
