### ISSUE TITLE
takePhotos does not work, even on the example project

### ISSUE THREAD

**Issue by Sh1d0w** [mikaoj/BSImagePicker#191]
This happens on freshly checkout repo and running the Example project

![](https://i.imgur.com/nheRYj1.jpg)

**Comment by mikaoj** [comment]
Have you tested on a device? Last time i checked the simulator didn't have a camera :)

**Comment by Sh1d0w** [comment]
Oh well, I feel stupid. Thanks, and sorry for bothering!
