### ISSUE TITLE
Can not get data from PHAsset

### ISSUE THREAD

**Issue by veila** [mikaoj/BSImagePicker#195]
Hi,
I am using bsImagePicker to pick some image and upload them to server.

I am using this method to get data from asset
                    PHImageManager.default().requestImageData(for: asset, options: nil
                        , resultHandler: { (imageData, dataUTI, orientation, info) in
                            if let dt = imageData {
                                self.listDataAddImage?.append(dt)
                            }
                    })
But imageData always 0 bytes.

When I try another method.
PHImageManager.default().requestImage(for: asset, targetSize: CGSize(width: 100, height: 100), contentMode: PHImageContentMode.aspectFill, options: options, resultHandler: { (image, info) in
                        let data = image!.pngData()
                        if let dt = data {
                        }
                    })
It's work. But I do not want set Size(100,100) when get data.
How can I get imageData when pick image from camera roll.

**Comment by kaiskolik** [comment]
Does this issue occur only for selecting images which are stored in iCloud? 
If so, set the options for your request and enable network access for the request. 

Read this: https://developer.apple.com/documentation/photokit/phimagerequestoptions/1616934-isnetworkaccessallowed
