### ISSUE TITLE
if I don't allow permisson to access my photos and I return to access photos again the alert of allow and don't allow doesn't appear!!! 

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [mikaoj/BSImagePicker#196]

**Comment by mikaoj** [comment]
Yes, thats a case that isn't handled. The dialog can't be triggered after the user has made a choice.
What you can do is before presenting the image picker check if PHPhotoLibrary.authorizationStatus() is .denied.

If so you'll have to show a view explaining how they go into Settings > Your app > And enable photo permission.

https://developer.apple.com/documentation/photokit/requesting_authorization_to_access_photos

In a future version I will remove all permission handling, that should be up to the app developer to handle. (!!!)
