### ISSUE TITLE
IB Designables: Failed to render and update auto layout status for

### ISSUE THREAD

**Issue by n1schal** [mikaoj/BSImagePicker#198]
IB Designables: Failed to render and update auto layout status for ... : dlopen(BSImagePicker.framework, 1): Library not loaded: @rpath/BSGridCollectionViewLayout.framework/BSGridCollectionViewLayout   Referenced from: BSImagePicker.framework   Reason: image not found

**Comment by mikaoj** [comment]
Checkout the latest tagged version (2.9.0 right now) as master is a state of being rewritten right now

**Comment by sudhanshuGrappus** [comment]
On the latest version (2.10) but still the same problem persists. Any updates on its solution ?

**Comment by mmbabaev** [comment]
still the same problem

**Comment by maaztausif** [comment]
Did anyone solve this problem?
