### ISSUE TITLE
dyld: Library not loaded: @rpath/BSImagePicker.framework/BSImagePicker

### ISSUE THREAD

**Issue by gralexey** [mikaoj/BSImagePicker#199]
Got this message trying to install Examples on the iPhone.

**Fixed by moving BSImagePicker.framework from "Linked Frameworks and Libraries" to "Embedded Binaries".** JFYI

**Describe the bug**
`dyld: Library not loaded: @rpath/BSImagePicker.framework/BSImagePicker` on app start on device. In simulator all is ok.

**To Reproduce**
1. Install app to the device
...
See dyld: Library not loaded: @rpath/BSImagePicker.framework/BSImagePicker

**Expected behavior**
Sound launch

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8+]
 - OS: [e.g. iOS12.1.2]

**BSImagePicker configuration**
Haven't touched anything.

**Comment by mikaoj** [comment]
Checkout the latest tagged version (2.9.0 right now) as master is a state of being rewritten right now
