### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by ruizmarc** [mikaoj/BSImagePicker#200]
Xcode 10.2 Beta now comes with Swift 5. 

Any plans on updating BSImagePicker to support it? 

Thanks for the work! :D

**Comment by mikaoj** [comment]
try 2.10.0

**Comment by ruizmarc** [comment]
Great! Thanks for the work! 

Updating my Podfile right now :)

**Comment by mikaoj** [comment]
Let me know if it works ^^

**Comment by ruizmarc** [comment]
After updating the pod, I'm getting the following warning:

```
:-1: ignoring build task 'ConstructedTask(forTarget: BSGridCollectionViewLayout, 3 inputs, 1 outputs, ruleInfo: ["CopyPlistFile", "/mypath/targetName-hhwqkvqhhakfhgbegnyfmpxvohva/Build/Products/Beta_debug-iphonesimulator/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/InfoSource.plist", "/mypath/Pods/BSGridCollectionViewLayout/Sources/InfoSource.plist"])' which produces files already produced by another task:
/mypath/targetName-hhwqkvqhhakfhgbegnyfmpxvohva/Build/Products/Beta_debug-iphonesimulator/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/InfoSource.plist
This warning represents an extremely serious project misconfiguration and will cause some build tasks in your project to be skipped entirely, leading to other build failures or missing files in the build directory. (in target 'BSGridCollectionViewLayout')
```

**Comment by yashwanth8803** [comment]
Showing All Messages
:-1: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'BSGridCollectionViewLayout')

**Comment by yashwanth8803** [comment]
:-1: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'BSImageView')

**Comment by yashwanth8803** [comment]
:-1: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'BSGridCollectionViewLayout')

**Comment by yashwanth8803** [comment]
Please try to solve this issue....

**Comment by ruizmarc** [comment]
I’m using it with Swift 5, without problems :) Try version 2.10.0

**Comment by yashwanth8803** [comment]
<img width="1397" alt="Screenshot 2019-05-06 at 12 10 53 PM" src="https://user-images.githubusercontent.com/44767995/57209895-0cdea080-6ff8-11e9-8e6a-5fe0555c7299.png">


see these errors i am getting now after updateing with BSImagePicker version 2.10.0

**Comment by yashwanth8803** [comment]
i am using pod 'BSImagePicker', '~> 2.10.0' now

**Comment by mikaoj** [comment]
Update to Xcode 10

**Comment by yashwanth8803** [comment]
yes, I am using Xcode 10.1

**Comment by yashwanth8803** [comment]
I am using xcode 10.1
 Am unable to see swift version 5.0 in my project build phases.

**Comment by yashwanth8803** [comment]
Which version is supported for swift 4.2 version, please let me know.

**Comment by mikaoj** [comment]
Use Xcode 10.2 :)
