### ISSUE TITLE
Allow option to disable live feed in CameraCell

### ISSUE THREAD

**Issue by coreysprague** [mikaoj/BSImagePicker#202]
I am working on multiple image selection for an app. This picker is by far the best option available to me. However, the live camera feed in the Camera cell is a show-stopper for my designer. In discussions, he wants to have the cell be a simple flat cell with the icon in the middle (similar to what is shown prior to the user giving camera permission).

Feature:
- create setting flag to enable live feed (default to ON)
- update CameraCell to disable live feed (likely, just augment the existing guard statement: https://github.com/mikaoj/BSImagePicker/blob/master/Sources/View/CameraCell.swift#L71)

I'd be happy to submit a PR with the necessary code to enable this configuration option, but I wanted to discuss first to see if there are any concerns with this approach before I start doing work.

**Comment by mikaoj** [comment]
Sounds straightforward enough. I'll probably merge something like that without asking any questions :)

**Comment by coreysprague** [comment]
Great. I'll try to get something submitted in the next couple of days!
