### ISSUE TITLE
Wrong target iOS version

### ISSUE THREAD

**Issue by jankase** [mikaoj/BSImagePicker#210]
**Describe the bug**
Project files specifies wrong target version (at least different than CocoaPods spec files). When try to use Carthage as dependency manager leads to compilation failure. I've submit pull request to fix this issue in BSImageView and BSGridCollectionViewLayout, but in this project is more complicated to do so, because of frameworks are included in the project. 

**To Reproduce**
1. Import BSImagePicker via Carthage into project with target version 11.0.
2. Try to compile the project. End with compilation error, that BSImagePicker is compiled for iOS 12.1 and is required 11.0.

**Expected behavior**
It will be to compile BSImagePicker on same versions as specified in Cocopods.

**Comment by mikaoj** [comment]
Thanks! Merged and taged new versions of BSGridCollectionViewLayout/BSImageView. Should fix the issue.
