### ISSUE TITLE
Only 1st 10 pics shown in All pics, no pics shown in other folders

### ISSUE THREAD

**Issue by johngithubby** [mikaoj/BSImagePicker#212]
**Describe the bug**
The picker only shows the first 10 pictures in All Photos (or no pictures at all in other folders). The rest are invisible, although when I tap the empty space where the rest of the pics are supposed to be, a grey square appears there with the number of the selected pic.

**To Reproduce**
Present the viewcontroller.

**Expected behavior**
See all pictures

**Smartphone (please complete the following information):**
 - Device: iPhone8 Plus
 - OS: iOS 12.2

**BSImagePicker configuration**
No config.
![IMG_5386](https://user-images.githubusercontent.com/11788725/57004216-47c97a00-6b9b-11e9-84f9-78c49a8e5bbf.jpg)

**Comment by mikaoj** [comment]
Are you using iCloud photos?
