### ISSUE TITLE
How to set default selections inside the image picker?

### ISSUE THREAD

**Issue by WaffleCohn** [mikaoj/BSImagePicker#215]
Hi, I was looking into setting photos as already selected when you open the `BSImagePickerViewController` and I had trouble figuring out how to do it properly. I see that there is a `defaultSelections` property, but this has a type of `PHFetchResult<PHAsset>?`. I want to be able to have photos that have been previously selected remain selected, but the image picker returns assets as a `[PHAsset]` and as far as I know there is no way to convert this to a `PHFetchResult<PHAsset>`. Does anybody have any recommendations for how to achieve this?

**Comment by basilmariano** [comment]
```
let vc = BSImagePickerViewController()
        vc.maxNumberOfSelections = numberOfSelections
        if let selectedAssets = self.selectedAssets {
            let collection = PHAssetCollection.transientAssetCollection(with: selectedAssets, title: "Selected Photos")
            vc.defaultSelections = PHAsset.fetchAssets(in: collection, options: nil)
        }
```

that is how i did it. so far it is working
**selectedAssets** are the previously selected assets from BSImagePickerViewController
