### ISSUE TITLE
app crashing when scrolling through photos

### ISSUE THREAD

**Issue by Marcoc88** [mikaoj/BSImagePicker#222]
**Describe the bug**
Scrolling through photos will cause the app to crash. Might be related to trying to download images from iCloud as you scroll. I am using the latest BSImagePicker just updated.

**To Reproduce**
1. Open the image picker. The default view is Recents
2. Begin scrolling down through your images
3. The app crashes
Thread 22: EXC_BAD_ACCESS (code=1, address=0x308c796eb000)

**Expected behavior**
App can scroll through photos without crashing.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13

**Comment by mikaoj** [comment]
Does it happen every time?
I can't reproduce it on my iPhone 7 running iOS 13.

**Comment by Marcoc88** [comment]
Happens every time for me on iPhone X iOS 13. Below are some of the crash logs.

`Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x000084f62f4eacd0
VM Region Info: 0x84f62f4eacd0 is not in any region.  Bytes after previous region: 146181616217297  
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO            0000000280000000-00000002a0000000 [512.0M] rw-/rwx SM=PRV  
--->  
      UNUSED SPACE AT END

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [1835]
Triggered by Thread:  1

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_pthread.dylib       	0x0000000182f1e0f0 _pthread_mutex_firstfit_lock_slow$VARIANT$armv81 + 224
1   CoreFoundation                	0x000000018317b384 __CFRunLoopDoObservers + 320
2   CoreFoundation                	0x000000018317b384 __CFRunLoopDoObservers + 320
3   CoreFoundation                	0x000000018317b9b0 __CFRunLoopRun + 1308
4   CoreFoundation                	0x000000018317b16c CFRunLoopRunSpecific + 464
5   GraphicsServices              	0x000000018cfb3328 GSEventRunModal + 104
6   UIKitCore                     	0x00000001871e5d0c UIApplicationMain + 1936
7   Timestamp                     	0x000000010472e7d0 0x1046d8000 + 354256
8   libdyld.dylib                 	0x0000000183006424 start + 4

Thread 1 name:  Dispatch queue: com.apple.photos.imageManagerCache
Thread 1 Crashed:
0   libobjc.A.dylib               	0x0000000182f28188 objc_msgSend + 8
1   CoreFoundation                	0x00000001830dec04 -[__NSDictionaryM objectForKeyedSubscript:] + 180
2   Photos                        	0x000000018e463780 -[PHCompositeMediaResult isDegraded] + 36
3   Photos                        	0x000000018e4bb964 -[PHCachingImageManager _canPopulateCacheForResult:] + 36
4   Photos                        	0x000000018e4be588 __90-[PHCachingImageManager additionalWorkForImageRequestCompletedWithResult:request:context:]_block_invoke + 64
5   libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
6   libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
7   libdispatch.dylib             	0x0000000182eae7c0 _dispatch_lane_serial_drain$VARIANT$armv81 + 564
8   libdispatch.dylib             	0x0000000182eaf1d8 _dispatch_lane_invoke$VARIANT$armv81 + 400
9   libdispatch.dylib             	0x0000000182eb84c0 _dispatch_workloop_worker_thread + 576
10  libsystem_pthread.dylib       	0x0000000182f20fa8 _pthread_wqthread + 276
11  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 2 name:  Dispatch queue: com.apple.figphoto.heif.workerQueue
Thread 2:
0   libsystem_kernel.dylib        	0x0000000182ffd9ec kevent_id + 8
1   libdispatch.dylib             	0x0000000182ebedd8 _dispatch_kq_poll + 328
2   libdispatch.dylib             	0x0000000182ebe404 _dispatch_event_loop_poke$VARIANT$armv81 + 636
3   Photos                        	0x000000018e4bb420 -[PHCachingImageManager additionalWorkForImageRequestCompletedWithResult:request:context:] + 152
4   Photos                        	0x000000018e612c38 __89-[PHImageManager requestNewCGImageForAsset:targetSize:contentMode:options:resultHandler:]_block_invoke + 1404
5   Photos                        	0x000000018e59ce58 -[PHImageRequestContext processMediaResult:forRequest:] + 408
6   Photos                        	0x000000018e492abc -[PHMediaRequestContext mediaRequest:didFinishWithResult:] + 136
7   Photos                        	0x000000018e47dec4 _finishRequest + 1348
8   Photos                        	0x000000018e4801e4 ___loadImageFromStoreAndKey_block_invoke + 832
9   Photos                        	0x000000018e6094e0 _decodeCallback + 96
10  MediaToolbox                  	0x000000018cbaebf4 __FigPhotoDecompressionSessionEnqueueAsynchronousRequest_block_invoke_2 + 172
11  libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
12  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
13  libdispatch.dylib             	0x0000000182eaaf3c _dispatch_continuation_pop$VARIANT$armv81 + 404
14  libdispatch.dylib             	0x0000000182eaa6b0 _dispatch_async_redirect_invoke + 592
15  libdispatch.dylib             	0x0000000182eb7194 _dispatch_root_queue_drain + 344
16  libdispatch.dylib             	0x0000000182eb7934 _dispatch_worker_thread2 + 116
17  libsystem_pthread.dylib       	0x0000000182f20f68 _pthread_wqthread + 212
18  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 3 name:  com.apple.uikit.eventfetch-thread
Thread 3:
0   libsystem_kernel.dylib        	0x0000000182fda5f4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x0000000182fd9a60 mach_msg + 72
2   CoreFoundation                	0x0000000183180918 __CFRunLoopServiceMachPort + 216
3   CoreFoundation                	0x000000018317ba38 __CFRunLoopRun + 1444
4   CoreFoundation                	0x000000018317b16c CFRunLoopRunSpecific + 464
5   Foundation                    	0x00000001834bb408 -[NSRunLoop+ 33800 (NSRunLoop) runMode:beforeDate:] + 228
6   Foundation                    	0x00000001834bb2e8 -[NSRunLoop+ 33512 (NSRunLoop) runUntilDate:] + 88
7   UIKitCore                     	0x000000018727caac -[UIEventFetcher threadMain] + 152
8   Foundation                    	0x00000001835eb884 __NSThread__start__ + 848
9   libsystem_pthread.dylib       	0x0000000182f201f0 _pthread_start + 124
10  libsystem_pthread.dylib       	0x0000000182f23af0 thread_start + 8

Thread 4 name:  com.apple.CoreMotion.MotionThread
Thread 4:
0   libsystem_kernel.dylib        	0x0000000182fda5f4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x0000000182fd9a60 mach_msg + 72
2   CoreFoundation                	0x0000000183180918 __CFRunLoopServiceMachPort + 216
3   CoreFoundation                	0x000000018317ba38 __CFRunLoopRun + 1444
4   CoreFoundation                	0x000000018317b16c CFRunLoopRunSpecific + 464
5   CoreFoundation                	0x000000018317beb8 CFRunLoopRun + 60
6   CoreMotion                    	0x000000018fa3bb24 0x18f955000 + 944932
7   libsystem_pthread.dylib       	0x0000000182f201f0 _pthread_start + 124
8   libsystem_pthread.dylib       	0x0000000182f23af0 thread_start + 8

Thread 5 name:  Dispatch queue: com.apple.figphoto.heif.feederQueue
Thread 5:
0   libsystem_kernel.dylib        	0x0000000182fda630 semaphore_wait_trap + 8
1   libdispatch.dylib             	0x0000000182ea2f38 _dispatch_sema4_wait$VARIANT$armv81 + 24
2   libdispatch.dylib             	0x0000000182ea3574 _dispatch_semaphore_wait_slow + 128
3   MediaToolbox                  	0x000000018cbaea98 __FigPhotoDecompressionSessionEnqueueAsynchronousRequest_block_invoke + 44
4   libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
5   libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
6   libdispatch.dylib             	0x0000000182eae7c0 _dispatch_lane_serial_drain$VARIANT$armv81 + 564
7   libdispatch.dylib             	0x0000000182eaf1d8 _dispatch_lane_invoke$VARIANT$armv81 + 400
8   libdispatch.dylib             	0x0000000182eb84c0 _dispatch_workloop_worker_thread + 576
9   libsystem_pthread.dylib       	0x0000000182f20fa8 _pthread_wqthread + 276
10  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 6 name:  Dispatch queue: com.apple.photos.imgmgr.ctxt.bgchooser
Thread 6:
0   libsystem_kernel.dylib        	0x0000000182ffbcdc __psynch_mutexwait + 8
1   libsystem_pthread.dylib       	0x0000000182f1e1a4 _pthread_mutex_firstfit_lock_wait + 92
2   libsystem_pthread.dylib       	0x0000000182f1e114 _pthread_mutex_firstfit_lock_slow$VARIANT$armv81 + 260
3   CoreMedia                     	0x000000018994b44c AccessManagedFile + 36
4   CoreMedia                     	0x000000018994b258 ManagedFileByteStreamCopyProperty + 56
5   CoreMedia                     	0x000000018993bbec GetEntireLengthOfByteStream + 76
6   CoreMedia                     	0x000000018993ba88 FigAtomStreamInitWithByteStreamWithSizeAndReporter + 76
7   MediaToolbox                  	0x000000018cb49d94 FigPhotoHEIFUtilitiesByteStreamHasMoovAtom + 48
8   MediaToolbox                  	0x000000018cb989e4 _openContainer + 96
9   MediaToolbox                  	0x000000018cd36de8 FigPhotoDecompressionContainerCreate + 332
10  Photos                        	0x000000018e6090f0 -[PHFigDecoder decodeImageFromData:orFileURL:maxSideLength:resizeMode:applyOrientationTransform:optimizeForDrawing:highPriority:waitUntilComplete:completion:] + 2124
11  Photos                        	0x000000018e599eb0 PHDecodeImageFromURLForRequest + 504
12  Photos                        	0x000000018e59a10c PHDecodeImageFromStoreForRequest + 400
13  Photos                        	0x000000018e47ece8 _imageResourceChooserHandler_block_invoke + 1188
14  Photos                        	0x000000018e5c7ba0 __55-[PHImageResourceChooser presentNextQualifyingResource]_block_invoke.55 + 1372
15  Photos                        	0x000000018e5822cc ___presentResourcesFromHintsUntilStop_block_invoke + 332
16  PhotoLibraryServices          	0x000000018dca5914 +[PLManagedAsset+ 5695764 (RM) enumerateImageRequestHintData:assetWidth:assetHeight:libraryID:startingOffset:block:] + 788
17  Photos                        	0x000000018e581fdc _presentResourcesFromHintsUntilStop + 360
18  Photos                        	0x000000018e583620 PHChooserListContinueEnumerating + 64
19  Photos                        	0x000000018e5c7154 -[PHImageResourceChooser presentNextQualifyingResource] + 1440
20  Photos                        	0x000000018e47bfb4 -[PHImageRequest startRequest] + 2040
21  libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
22  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
23  libdispatch.dylib             	0x0000000182eae7c0 _dispatch_lane_serial_drain$VARIANT$armv81 + 564
24  libdispatch.dylib             	0x0000000182eaf20c _dispatch_lane_invoke$VARIANT$armv81 + 452
25  libdispatch.dylib             	0x0000000182eb84c0 _dispatch_workloop_worker_thread + 576
26  libsystem_pthread.dylib       	0x0000000182f20fa8 _pthread_wqthread + 276
27  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 7:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 10 name:  Dispatch queue: com.apple.photos.imgmgr.iodecode.activerequests
Thread 10:
0   libz.1.dylib                  	0x00000001b76e89ec inflate + 4988
1   libz.1.dylib                  	0x00000001b76e8794 inflate + 4388
2   ImageIO                       	0x0000000183b440a0 png_read_IDAT_data + 412
3   ImageIO                       	0x0000000183b861c4 _cg_png_read_row + 220
4   ImageIO                       	0x00000001839f1a50 PNGReadPlugin::DecodeFrameStandard+ 485968 (IIOImageReadSession*, ReadPluginData const&, PNGPluginData const&, IIODecodeFrameParams&) + 1400
5   ImageIO                       	0x00000001839f1400 PNGReadPlugin::DecodeUncomposedFrames+ 484352 (IIOImageRead*, GlobalPNGInfo*, ReadPluginData const&, PNGPluginData const&, std::__1::vector<IIODecodeFrameParams, std::__1::allocator<IIODecodeFrameParams> >&) + 96
6   ImageIO                       	0x00000001839f0db8 PNGReadPlugin::copyImageBlockSet+ 482744 (InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 4264
7   ImageIO                       	0x00000001839ed4e8 IIO_Reader::CopyImageBlockSetProc+ 468200 (void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 140
8   ImageIO                       	0x00000001839f9680 IIOImageProviderInfo::CopyImageBlockSetWithOptions+ 517760 (void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 1216
9   CoreGraphics                  	0x000000018a114330 imageProvider_retain_data + 88
10  CoreGraphics                  	0x0000000189f15b9c CGDataProviderRetainData + 84
11  CoreGraphics                  	0x000000018a07ecc8 provider_for_destination_retain_data + 24
12  CoreGraphics                  	0x0000000189f15b9c CGDataProviderRetainData + 84
13  CoreGraphics                  	0x000000018a103d98 CGAccessSessionCreate + 104
14  CoreGraphics                  	0x0000000189fea0e4 get_access_session + 48
15  CoreGraphics                  	0x0000000189fe8e40 img_raw_read + 908
16  CoreGraphics                  	0x0000000189fee8c4 img_interpolate_read + 716
17  CoreGraphics                  	0x0000000189ff3764 img_data_lock + 9488
18  CoreGraphics                  	0x0000000189fefa4c CGSImageDataLock + 1120
19  CoreGraphics                  	0x0000000189e20e34 ripc_AcquireRIPImageData + 712
20  CoreGraphics                  	0x000000018a00a934 ripc_DrawImage + 1112
21  CoreGraphics                  	0x0000000189ff6630 CGContextDrawImageWithOptions + 1212
22  ImageIO                       	0x00000001839ff254 CGImageCreateCopyWithParametersNew+ 541268 (CGImage*, CGColor*, CGAffineTransform, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, CGColorSpace*, unsigned int, bool, CGColorRenderingIntent, CGInterpolationQuality, bool) + 1628
23  ImageIO                       	0x00000001839d6e64 IIOImageSource::createThumbnailAtIndex+ 376420 (unsigned long, IIODictionary*) + 3112
24  ImageIO                       	0x00000001839d9f00 CGImageSourceCreateThumbnailAtIndex + 360
25  Photos                        	0x000000018e4af544 _createDecodedImageUsingImageIOWithFileUrlOrData + 464
26  Photos                        	0x000000018e4af7b8 __184-[PHImageIODecoder decodeImageFromData:orFileURL:maxSideLength:resizeMode:applyOrientationTransform:optimizeForDrawing:highPriority:waitUntilComplete:existingRequestHandle:completion:]_block_invoke_2 + 80
27  libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
28  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
29  libdispatch.dylib             	0x0000000182eaaf3c _dispatch_continuation_pop$VARIANT$armv81 + 404
30  libdispatch.dylib             	0x0000000182eaa6b0 _dispatch_async_redirect_invoke + 592
31  libdispatch.dylib             	0x0000000182eb7194 _dispatch_root_queue_drain + 344
32  libdispatch.dylib             	0x0000000182eb7934 _dispatch_worker_thread2 + 116
33  libsystem_pthread.dylib       	0x0000000182f20f68 _pthread_wqthread + 212
34  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 11:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 12 name:  Dispatch queue: com.apple.photos.imgmgr.iodecode.activerequests
Thread 12:
0   libsystem_platform.dylib      	0x0000000182f119d4 _platform_memmove + 212
1   CoreGraphics                  	0x000000018a1141a8 imageProvider_getBytesAtPosition + 552
2   CoreGraphics                  	0x0000000189f155c0 CGDataProviderDirectGetBytesAtPositionInternal + 332
3   CoreGraphics                  	0x000000018a07eec0 provider_for_destination_get_bytes_at_position_inner + 432
4   CoreGraphics                  	0x0000000189f155c0 CGDataProviderDirectGetBytesAtPositionInternal + 332
5   CoreGraphics                  	0x000000018a1040cc get_chunks_direct + 228
6   CoreGraphics                  	0x0000000189fe8ebc img_raw_read + 1032
7   CoreGraphics                  	0x0000000189fee8c4 img_interpolate_read + 716
8   CoreGraphics                  	0x0000000189ff3764 img_data_lock + 9488
9   CoreGraphics                  	0x0000000189fefa4c CGSImageDataLock + 1120
10  CoreGraphics                  	0x0000000189e20e34 ripc_AcquireRIPImageData + 712
11  CoreGraphics                  	0x000000018a00a934 ripc_DrawImage + 1112
12  CoreGraphics                  	0x0000000189ff6630 CGContextDrawImageWithOptions + 1212
13  ImageIO                       	0x00000001839ff254 CGImageCreateCopyWithParametersNew+ 541268 (CGImage*, CGColor*, CGAffineTransform, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, CGColorSpace*, unsigned int, bool, CGColorRenderingIntent, CGInterpolationQuality, bool) + 1628
14  ImageIO                       	0x00000001839d6e64 IIOImageSource::createThumbnailAtIndex+ 376420 (unsigned long, IIODictionary*) + 3112
15  ImageIO                       	0x00000001839d9f00 CGImageSourceCreateThumbnailAtIndex + 360
16  Photos                        	0x000000018e4af544 _createDecodedImageUsingImageIOWithFileUrlOrData + 464
17  Photos                        	0x000000018e4af7b8 __184-[PHImageIODecoder decodeImageFromData:orFileURL:maxSideLength:resizeMode:applyOrientationTransform:optimizeForDrawing:highPriority:waitUntilComplete:existingRequestHandle:completion:]_block_invoke_2 + 80
18  libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
19  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
20  libdispatch.dylib             	0x0000000182eaaf3c _dispatch_continuation_pop$VARIANT$armv81 + 404
21  libdispatch.dylib             	0x0000000182eaa6b0 _dispatch_async_redirect_invoke + 592
22  libdispatch.dylib             	0x0000000182eb7194 _dispatch_root_queue_drain + 344
23  libdispatch.dylib             	0x0000000182eb7934 _dispatch_worker_thread2 + 116
24  libsystem_pthread.dylib       	0x0000000182f20f68 _pthread_wqthread + 212
25  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 13 name:  Dispatch queue: com.apple.photos.imgmgr.iodecode.activerequests
Thread 13:
0   libz.1.dylib                  	0x00000001b76ed768 0x1b76e2000 + 46952
1   libz.1.dylib                  	0x00000001b76ed91c 0x1b76e2000 + 47388
2   ImageIO                       	0x0000000183b440a0 png_read_IDAT_data + 412
3   ImageIO                       	0x0000000183b861c4 _cg_png_read_row + 220
4   ImageIO                       	0x00000001839f1a50 PNGReadPlugin::DecodeFrameStandard+ 485968 (IIOImageReadSession*, ReadPluginData const&, PNGPluginData const&, IIODecodeFrameParams&) + 1400
5   ImageIO                       	0x00000001839f1400 PNGReadPlugin::DecodeUncomposedFrames+ 484352 (IIOImageRead*, GlobalPNGInfo*, ReadPluginData const&, PNGPluginData const&, std::__1::vector<IIODecodeFrameParams, std::__1::allocator<IIODecodeFrameParams> >&) + 96
6   ImageIO                       	0x00000001839f0db8 PNGReadPlugin::copyImageBlockSet+ 482744 (InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 4264
7   ImageIO                       	0x00000001839ed4e8 IIO_Reader::CopyImageBlockSetProc+ 468200 (void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 140
8   ImageIO                       	0x00000001839f9680 IIOImageProviderInfo::CopyImageBlockSetWithOptions+ 517760 (void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 1216
9   CoreGraphics                  	0x000000018a114330 imageProvider_retain_data + 88
10  CoreGraphics                  	0x0000000189f15b9c CGDataProviderRetainData + 84
11  CoreGraphics                  	0x000000018a07ecc8 provider_for_destination_retain_data + 24
12  CoreGraphics                  	0x0000000189f15b9c CGDataProviderRetainData + 84
13  CoreGraphics                  	0x000000018a103d98 CGAccessSessionCreate + 104
14  CoreGraphics                  	0x0000000189fea0e4 get_access_session + 48
15  CoreGraphics                  	0x0000000189fe8e40 img_raw_read + 908
16  CoreGraphics                  	0x0000000189fee8c4 img_interpolate_read + 716
17  CoreGraphics                  	0x0000000189ff3764 img_data_lock + 9488
18  CoreGraphics                  	0x0000000189fefa4c CGSImageDataLock + 1120
19  CoreGraphics                  	0x0000000189e20e34 ripc_AcquireRIPImageData + 712
20  CoreGraphics                  	0x000000018a00a934 ripc_DrawImage + 1112
21  CoreGraphics                  	0x0000000189ff6630 CGContextDrawImageWithOptions + 1212
22  ImageIO                       	0x00000001839ff254 CGImageCreateCopyWithParametersNew+ 541268 (CGImage*, CGColor*, CGAffineTransform, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, CGColorSpace*, unsigned int, bool, CGColorRenderingIntent, CGInterpolationQuality, bool) + 1628
23  ImageIO                       	0x00000001839d6e64 IIOImageSource::createThumbnailAtIndex+ 376420 (unsigned long, IIODictionary*) + 3112
24  ImageIO                       	0x00000001839d9f00 CGImageSourceCreateThumbnailAtIndex + 360
25  Photos                        	0x000000018e4af544 _createDecodedImageUsingImageIOWithFileUrlOrData + 464
26  Photos                        	0x000000018e4af7b8 __184-[PHImageIODecoder decodeImageFromData:orFileURL:maxSideLength:resizeMode:applyOrientationTransform:optimizeForDrawing:highPriority:waitUntilComplete:existingRequestHandle:completion:]_block_invoke_2 + 80
27  libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
28  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
29  libdispatch.dylib             	0x0000000182eaaf3c _dispatch_continuation_pop$VARIANT$armv81 + 404
30  libdispatch.dylib             	0x0000000182eaa6b0 _dispatch_async_redirect_invoke + 592
31  libdispatch.dylib             	0x0000000182eb7194 _dispatch_root_queue_drain + 344
32  libdispatch.dylib             	0x0000000182eb7934 _dispatch_worker_thread2 + 116
33  libsystem_pthread.dylib       	0x0000000182f20f68 _pthread_wqthread + 212
34  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 14 name:  Dispatch queue: com.apple.figphoto.heif.workerQueue
Thread 14:
0   libsystem_kernel.dylib        	0x0000000182fda648 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	0x0000000182ea2fb4 _dispatch_sema4_timedwait$VARIANT$armv81 + 64
2   libdispatch.dylib             	0x0000000182ea353c _dispatch_semaphore_wait_slow + 72
3   MediaToolbox                  	0x000000018cba1018 HEIFItemDecoderWaitForFinishAndReturnStatus + 112
4   MediaToolbox                  	0x000000018cba10a0 HEIFItemDecoderRelease + 36
5   MediaToolbox                  	0x000000018cb9fc0c _decodeItem + 9384
6   MediaToolbox                  	0x000000018cb9d210 _applyDecodeStrategy + 324
7   MediaToolbox                  	0x000000018cb9c6c0 _decodeImage + 336
8   MediaToolbox                  	0x000000018cb99b00 _runAsyncDecodeRequest + 584
9   MediaToolbox                  	0x000000018cbaeb80 __FigPhotoDecompressionSessionEnqueueAsynchronousRequest_block_invoke_2 + 56
10  libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
11  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
12  libdispatch.dylib             	0x0000000182eaaf3c _dispatch_continuation_pop$VARIANT$armv81 + 404
13  libdispatch.dylib             	0x0000000182eaa6b0 _dispatch_async_redirect_invoke + 592
14  libdispatch.dylib             	0x0000000182eb7194 _dispatch_root_queue_drain + 344
15  libdispatch.dylib             	0x0000000182eb7934 _dispatch_worker_thread2 + 116
16  libsystem_pthread.dylib       	0x0000000182f20f68 _pthread_wqthread + 212
17  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 15 name:  Dispatch queue: canvasTransferQueue
Thread 15:
0   libsystem_malloc.dylib        	0x0000000182eec888 nanov2_free_to_block$VARIANT$armv81 + 272
1   CoreFoundation                	0x00000001830ddd24 -[__NSDictionaryM dealloc] + 128
2   CoreFoundation                	0x00000001830ddd24 -[__NSDictionaryM dealloc] + 128
3   CoreVideo                     	0x000000018ff163a8 CVBuffer::finalize+ 107432 () + 52
4   CoreVideo                     	0x000000018ff17c80 CVPixelBuffer::finalize+ 113792 () + 164
5   CoreFoundation                	0x00000001831826d8 _CFRelease + 208
6   CoreFoundation                	0x0000000183233428 cow_cleanup + 168
7   CoreFoundation                	0x00000001830ddd34 -[__NSDictionaryM dealloc] + 144
8   MediaToolbox                  	0x000000018cba16b8 ___canvasItemDecodeCallback_block_invoke + 148
9   libdispatch.dylib             	0x0000000182ed0658 _dispatch_call_block_and_release + 24
10  libdispatch.dylib             	0x0000000182ed11cc _dispatch_client_callout + 16
11  libdispatch.dylib             	0x0000000182eae7c0 _dispatch_lane_serial_drain$VARIANT$armv81 + 564
12  libdispatch.dylib             	0x0000000182eaf1d8 _dispatch_lane_invoke$VARIANT$armv81 + 400
13  libdispatch.dylib             	0x0000000182eb84c0 _dispatch_workloop_worker_thread + 576
14  libsystem_pthread.dylib       	0x0000000182f20fa8 _pthread_wqthread + 276
15  libsystem_pthread.dylib       	0x0000000182f23ae4 start_wqthread + 8

Thread 16:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	0x0000000182f23adc start_wqthread + 0

Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x000084f62f4eacd0   x1: 0x00000001ba252e88   x2: 0x00000001c1003c68   x3: 0x000000016b8c6a08
    x4: 0x00000000004f4005   x5: 0x0000000000000010   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000003   x9: 0x0000000000000003  x10: 0x000000000000001a  x11: 0x0000000000000000
   x12: 0x0000000000000005  x13: 0x00000001c7f55470  x14: 0x000000000000001b  x15: 0x00000001ca43d55a
   x16: 0x00000001c7f55470  x17: 0x00000001830db924  x18: 0x0000000000000000  x19: 0x00000001c1003c68
   x20: 0x00000001ba252e88  x21: 0x0000000000000003  x22: 0x0000000282f5acd0  x23: 0x0000000000000003
   x24: 0x0000000000000001  x25: 0x0000000000000000  x26: 0x00000001bf7db7c8  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016b8c6850   lr: 0x00000001830dec04
    sp: 0x000000016b8c6810   pc: 0x0000000182f28188 cpsr: 0x20000000
   esr: 0x92000004 (Data Abort) byte read Translation fault`

**Comment by Marcoc88** [comment]
This resolved itself with iOS 13.1. Must have been a bug with iOS 13.
