### ISSUE TITLE
HEIC Formats

### ISSUE THREAD

**Issue by malikdoksoz** [mikaoj/BSImagePicker#224]
I'm using this library on the flutter framework.But heic, heif formats can not display. Flutter has no support. Can the library have the option to convert up to 10-15 images(max) to jpg format? Im using this library https://github.com/Sh1d0w/multi_image_picker . I would be very happy if this feature was added.

**Comment by Sh1d0w** [comment]
The multi_image_picker library already converts the image to JPEG when you request the image data.
