### ISSUE TITLE
Add Windows Share (SMB) folder to select images

### ISSUE THREAD

**Issue by EricPreventa** [mikaoj/BSImagePicker#227]
Any plans to add in a windows share folder (SMB or SAMBA) to this file picker? Instead of being forced to select from the local folder?

There are many packages that very easily do this
https://github.com/shaojiankui/samba-iOS
https://github.com/TimOliver/TOSMBClient
https://github.com/amosavian/AMSMB2

**Comment by mikaoj** [comment]
No. But you aren't forced to select from local folder, it supports iCloud photos.
