### ISSUE TITLE
Filter out images to a given filename

### ISSUE THREAD

**Issue by EricPreventa** [mikaoj/BSImagePicker#228]
Any chance we can have a filtering parameter on file name? So for instance it'll only show up in the image picker whatever we tell it to disclose e.g. (*.png) or (amazingPics.*)

**Comment by mikaoj** [comment]
It uses Apples PhotoKit for fetching, sorting, filtering, etc.
And I don't believe they support filtering on filename, see https://developer.apple.com/documentation/photokit/phfetchoptions
