### ISSUE TITLE
localizations function is incomplete on iOS platform

### ISSUE THREAD

**Issue by glennWang** [mikaoj/BSImagePicker#229]
As the title say, localizations function is incomplete on iOS platform.

My iOS simulator is already selecting simple-Chinese, however, upper-right corner still display English "Done".

And, I think a fraction like 2/3  will be better than only a number.

![image](https://user-images.githubusercontent.com/7918942/68936150-e97d8500-07d4-11ea-8915-74ea8dc13c32.png)

**Comment by mikaoj** [comment]
You have to localize Done yourself. Look into how localization works on iOS.
But basically you create a localizable.strings and add "Done" = "做完了";
If you run into problems let me know and I'll see what I can do.

And as for 2/3 - sure that works. But the default is to allow Int.max selections (the maximum of a 64 bit int on most platforms) so 2/9,223,372,036,854,775,807 would look kind of bad ;)

**Comment by glennWang** [comment]
OK, I see.

Thanks for your timely response.

**Comment by krummler** [comment]
Hi there, 

To follow up on that,
would it be possible to make the used key configurable? We use a set of rules to define the keys used for translations. Currently this is a private let:

`private let doneBarButtonTitle: String = NSLocalizedString("Done", comment: "Done")`

Having a key "Done" doesn't match the rest and could be confusing for us. Would you mind changing this so a public var, so it can be overridden?

**Comment by mikaoj** [comment]
Yes - I have been meaning to change the key to something like BSImagePicker.done to distinguish it from similar keys that may already exist in the app.

Make it public and send a pull request :)
