### ISSUE TITLE
Set delegate methods?

### ISSUE THREAD

**Issue by SteveLobdell** [mikaoj/BSImagePicker#230]
I've just started out using Swift 5 so I'm still getting used to it.  But I'm not able to use the BSPresentViewController method the way SwiftUI works.  And there's no other way to set a delegate to receive the picker events.  Am I missing something?

**Comment by mikaoj** [comment]
No not in any of the 2.x releases or master branch.
You could give the develop branch a go which has a public delegate property you can set.
