### ISSUE TITLE
Take multiple photos with camera

### ISSUE THREAD

**Issue by SteveLobdell** [mikaoj/BSImagePicker#232]
**Is your feature request related to a problem? Please describe.**
Don't think so

**Describe the solution you'd like**
This is a really nice image picker that allows for multi-selecting images, so it would be nice, as least as a configuration, to be able to press the camera and snap multiple photos before manually dismissing the camera manually.

**Describe alternatives you've considered**

**Additional context**

**Comment by brux88** [comment]
the same problem

**Comment by mikaoj** [comment]
Yeapp...it is something that I want to add. But it will take some time

**Comment by tatuanfpt** [comment]
Hi guys,
Do we have any update on this feature ?
