### ISSUE TITLE
Crash when hide app and take photo

### ISSUE THREAD

**Issue by IldarMurzenkov** [mikaoj/BSImagePicker#24]
Hi!
If i minimize the application during BSImagePicker is open, and then take picture by camera, after when i return back to the application i have fatal error in BSImagePicker.AssetsModel.photoLibraryDidChange:

fatal error: unexpectedly found nil while unwrapping an Optional value

i use SDK 8.3, deployment target :8.2 (iphone 5s)

**Comment by mikaoj** [comment]
This should be fixed in the develop branch

**Comment by mikaoj** [comment]
And thanks for taking the time to write an issue! :)

**Comment by mikaoj** [comment]
I could probably do a 1.0.1 from develop now, with that fix

**Comment by mikaoj** [comment]
1.0.1 is out which should fix this issue

**Comment by IldarMurzenkov** [comment]
Thanks! I will try it )
