### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by josharnoldjosh** [mikaoj/BSImagePicker#246]
Hello.

Is it possible to automatically have the option to switch between "Favourites" or other already existing album types? How can I do this?

Also, when I run the example, there is no option to switch albums in the navigation bar. How can I add this option? Do I have to update `PFFetchResult` ? Thanks!

**Comment by mikaoj** [comment]
I'm not sure I understand your first question. Isn't it the same as the second one?

As for your second question. Yes you can set the fetch options in settings to include the albums you want.
In the comment above it there are examples of commonly used 'albums'.

**Comment by josharnoldjosh** [comment]
Yes, I think you understood correctly. I want to have `navigationItem.titleView` a drop down menu in which I can select "favourites". What's the general approach to this. Do I have to figure out what assets go into the "favourite" category myself, then pass it as the `PFFetchResult` ? Thanks

**Comment by logananderson** [comment]
I think the question @josharnoldjosh is asking is: Why does he never see albums at the top of the ImagePickerController?  I'm having the same issue.  As far as I can tell, https://github.com/mikaoj/BSImagePicker/blob/master/Sources/Controller/ImagePickerController.swift#L50 `albums` is always size 1 and is the album `Recent.`  This of course means that `albumButton` is hidden.  Unsure why the fetching of albums isn't working.. attempting to look into it.

**Comment by logananderson** [comment]
Ah, I see.  Adding to https://github.com/mikaoj/BSImagePicker/blob/master/Sources/Model/Settings.swift#L118 seems to have produced my desired results.

**Comment by mikaoj** [comment]
Yeah I've experimenting with having the default to only use one asset collection that simply contains all images.
Maybe I'll revert that experiment and enable them all as default again. But as you've discovered you can set whichever you want and if there are more than 1 the button will show up.
