### ISSUE TITLE
How to use this with an Objective-C project?

### ISSUE THREAD

**Issue by miguelpruivo** [mikaoj/BSImagePicker#248]
This might sound like a dumb question, but, how can I use it? I've added the pod, but so far, I can only seem to get this import:
```
#import "BSImagePicker-prefix.pch"
```
Which is not I want. 

Thanks!

**Comment by mikaoj** [comment]
I haven't tried it in Objective-C for a while. So maybe it doesn't work.
Otherwise I think the import should be: ```#import <BSImagePicker/BSImagePicker.h>```
Or ```@import BSImagePicker;```

You could always do a swift extension where you want to use it and start to introduce swift in your codebase ;).
So if you have MyViewController.h/m:
```objectivec
@interface MyViewController: UIViewController
...
@end
```

Then create MyViewController+ImagePicker.swift:
```swift
import BSImagePicker

extension MyViewController {
    @objc
    func presentImagePicker() {
         // Setup and present image picker here
         // and call this function from objective-c class ^^
    }
}
```

**Comment by miguelpruivo** [comment]
@mikaoj based on #169 it looks like is using only Objective-C code, am I wrong?

**Comment by miguelpruivo** [comment]
Also, @mikaoj I've tried your solution, but I'm working on a Pod lib, and mixing Swift files with Obj-C doesn't seem to work properly.

**Comment by miguelpruivo** [comment]
@mikaoj ok, further investigation on this let me to find that you somehow forgot to expose (mark as public `@objc` methods) since version 3.0.0 I believe.

That way, it's quite hard for me to integrate with my Pod lib. I can do it easily for versions below 3.0.0, but then I loose video support which I want to. With your latest versions, I can't access any of the functionalities from the package.

Thank you!

**Comment by mikaoj** [comment]
> ok, further investigation on this let me to find that you somehow forgot to expose (mark as public @objc methods) since version 3.0.0 I believe.
Create a pull-request with any @objc you need :)

**Comment by miguelpruivo** [comment]
Thanks! There you have it @mikaoj. Check #251.
