### ISSUE TITLE
Crash just after presenting picker view. if coredata concurrency debug option enabled.

### ISSUE THREAD

**Issue by itsSaad** [mikaoj/BSImagePicker#25]
My app crashes after the picker view is presented. I have enabled the coredata concurrency debugging option with the following in build arguments: `-com.apple.CoreData.ConcurrencyDebug 1`.

Seems like its using NSManagedObjectContext the wrong way. Although i don't know if this library uses it or its just ALAssetsLibrary messing up.

**Comment by mikaoj** [comment]
Thanks for submitting an issue, but I need more info :)

Which version of image picker?
Which iOS version?
Device?
Crash log?

BSImagePicker doesn't use core data

**Comment by mikaoj** [comment]
I'm closing this one as I didn't receive any more info and couldn't reproduce it myself.
