### ISSUE TITLE
Package upload error report

### ISSUE THREAD

**Issue by luowenx** [mikaoj/BSImagePicker#250]
Verify your bundle id 'org.cocoapods.BSGridCollectionViewLayout' is correct.

**Comment by mikaoj** [comment]
Needs much more info

**Comment by luowenx** [comment]
> Needs much more info

ok

**Comment by mikaoj** [comment]
When and where are you seeing this message?
What are the steps to reproduce it?

Looks like you are using cocoapods, how does your Podfile look and which version of cocoapods are you using? Please add as much details as possible to be able to understand and solve it.
