### ISSUE TITLE
func imagePicker(_ imagePicker: ImagePickerController, didReachSelectionLimit count: Int)没有地方调用

### ISSUE THREAD

**Issue by yzl140520** [mikaoj/BSImagePicker#255]
/// Selection limit reach
    /// - Parameter imagePicker: The image picker that selection limit was reached in.
    /// - Parameter count: Number of selected assets.
    func imagePicker(_ imagePicker: ImagePickerController, didReachSelectionLimit count: Int)
没地方调用

**Comment by mikaoj** [comment]
?

**Comment by yzl140520** [comment]
我们需要实现选择图片时，超过设定数据时，弹出提示，但是超过设定数据，你有没调func imagePicker(_ imagePicker: ImagePickerController, didReachSelectionLimit count: Int)代理

**Comment by janewu77** [comment]
> 我们需要实现选择图片时，超过设定数据时，弹出提示，但是超过设定数据，你有没调func imagePicker(_ imagePicker: ImagePickerController, didReachSelectionLimit count: Int)代理

try this: (先设定这个参数）
vc.maxNumberOfSelections = 5  

you might search these in the source code , these might help
然后是要写一个Closure的，你具体可以搜下面的代码去看说明。
imagePicker.photosViewController.selectLimitReachedClosure = selectLimitReached
//parameter selectLimitReached: Closure to call when user reaches selection limit or nil

p.s.建议提问用英文 Please use English
