### ISSUE TITLE
hello, is it possible to push to next controller when i press done button?

### ISSUE THREAD

**Issue by cliff357** [mikaoj/BSImagePicker#259]
Please kindly help, thank you
I don't want to dismiss imagePicker when I press done

**Comment by mikaoj** [comment]
If you have a look at Settings.swift which covers most of the things you want to tweak there is a flag that sound like it does what you want:
```
        /// Should the image picker dismiss when done/cancelled
        public lazy var enabled = true
```

So doing something like: 
```
settings.dismiss.enabled = false
```
Might be what you are looking for.

**Comment by cliff357** [comment]
thanks for quick reply

**Comment by cliff357** [comment]
One more question, I want to push to other controller from imagePicker after press "Done"

But how can i do that, i tried these code but not work , sad, Would you mind to help? thanks
@mikaoj 


`presentImagePicker(imagePicker, select: { (asset) in }, deselect: { (asset) in}, cancel: { (assets) in}, finish: { (assets) in`
`imagePicker.pushViewController(UIViewController(), animated: true)`
`})`

**Comment by cliff357** [comment]
@mikaoj  sorry for asking one more question. 

How can I push to next controller when user press "Done" in imagePicker?
