### ISSUE TITLE
Customize Navigation Bar colors

### ISSUE THREAD

**Issue by rgallagher27** [mikaoj/BSImagePicker#26]
Is it possible to customise the navigation bar header text colour and the dismiss X UIButton colour?

**Comment by mikaoj** [comment]
Much of the customisation was droppped when i did the 1.0 rewrite.
But I'm planning to add them again, probably in 1.1

For now you will probably have to use UIApperance to change color on UIBarButtonItem...but that will change the color on both of them

**Comment by mikaoj** [comment]
Perhaps I'll do 1.1 tonight if i got the time :)

**Comment by mikaoj** [comment]
1.1.0 is now out which gives you access to cancel, album and done buttons. Tweak them so they fit your needs :)

Thanks for submitting an issue!
