### ISSUE TITLE
Crash when trying to set dismiss = false. 

### ISSUE THREAD

**Issue by cliff357** [mikaoj/BSImagePicker#261]
Sorry, need your help again. 
after i pod the latest version. and trying to push to new controller, crash occur

let bsimagePicker = ImagePickerController(selectedAssets: assets)
bsimagePicker.settings.dismiss.enabled = false   **<---- Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)**

Would you mind to have a check?

**Comment by mikaoj** [comment]
I'm doing the same thing and it doesn't crash.

**Comment by cliff357** [comment]
running on iPhone 11 pro max , 13.4.1 simulator 
clean build
xcode 11.4.1

What can i do?

**Comment by cliff357** [comment]
wow, need to remove BSImagepicker from pod and pod again, problem solved :)
No idea why this happens
