### ISSUE TITLE
Get image(single or multiple) when finished selected

### ISSUE THREAD

**Issue by OudomSec** [mikaoj/BSImagePicker#263]
**I know these function is use to control when we select, deselect or finish.**

```
self.presentImagePicker(imagePicker, select: { (asset) in
      print("Selected: \(asset)")
    }, deselect: { (asset) in
      print("Deselected: \(asset)")
    }, cancel: { (assets) in
      print("Canceled with selections: \(assets)")
    }, finish: { (assets) in
      print("Finished with selections: \(assets)")
    })
```

But I want to get selected image when finished, but I don't know how to get the image when click "done" button, please help.

**Comment by mikaoj** [comment]
It seems to me that you've answered your own question.

> I know these function is use to control when we select, deselect or finish.
> ...
> But I want to get selected image when finished

The finish closure will be called with the selected assets when you press done.

Or is the question how you fetch an image for an [PHAsset](https://developer.apple.com/documentation/photokit/phasset)
A quick look in the documentation, source code or a search in your favorite search engine would have given you an answer like this:

```swift
let imageManager = PHCachingImageManager.default()

// Set which size, contentMode and any optional options you want for the image
imageManager.requestImage(for: asset, targetSize: targetSize, contentMode: .aspectFill, options: nil) { (image, _) in
    guard let image = image else { return }
    // Do something with image
}
```

[PHImageManager documentation](https://developer.apple.com/documentation/photokit/phimagemanager)
[PHImageRequestOptions documentation](https://developer.apple.com/documentation/photokit/phimagerequestoptions)

**Comment by OudomSec** [comment]
It's work now, thank you very much.
