### ISSUE TITLE
Permission is asked only Once

### ISSUE THREAD

**Issue by ersel95** [mikaoj/BSImagePicker#272]
If user does not give permission to gallery access, permission is not being asked for the second time.

**Comment by nickdnk** [comment]
This is an iOS limitation. The user will have to go into settings and change the permission after they initially said no.

**Comment by mikaoj** [comment]
This ^^

Maybe some helper methods for checking permissions could be exposed or showing some message.
I've intentionally tried to stay away from handling user facing messages to avoid having to handle localization.
