### ISSUE TITLE
attempt to delete and reload the same index path (<NSIndexPath: 0xd88f329bfe16a05b> {length = 2, path = 1 - 0})

### ISSUE THREAD

**Issue by SushreeNayak** [mikaoj/BSImagePicker#274]
<img width="911" alt="Screen Shot 2020-06-23 at 5 42 33 PM" src="https://user-images.githubusercontent.com/15657892/85467253-f9362680-b578-11ea-801e-1066f37c5ba2.png">

**Comment by knox** [comment]
This might be a regression of or is related to #254

**Comment by nayaks2019** [comment]
Thank you so much for fixing this issue.When it is going to be released any idea?Need this urgently

**Comment by nayaks2019** [comment]
Thank you for fixing this issue.When It is going to be released?

**Comment by knox** [comment]
You can install the fixed code directly from master like this
`pod 'BSImagePicker', :git => 'https://github.com/mikaoj/BSImagePicker.git', :branch => 'master'`

**Comment by mikaoj** [comment]
I'll probably release a version in a day or two. You can do what @knox said if you need it now.
Or specify a commit instead of branch if you prefer that:
```
pod 'BSImagePicker', :git => 'https://github.com/mikaoj/BSImagePicker.git', :commit => 'ea583325d1e5e7eddbf9074d11ebb94b0f0a0253'
```

**Comment by mikaoj** [comment]
Ok...I did it now. Version 3.2.1

**Comment by nayaks2019** [comment]
Thanks @mikaoj 
Wha is the minimum OS version is supported by BSImagepicker?

**Comment by nayaks2019** [comment]
@mikaoj @knox it is no more supported by Objective c?

**Comment by mikaoj** [comment]
What isn’t supported by objective-c?

**Comment by nayaks2019** [comment]
@mikaoj  yes I was using 2.10.3 version which was working with objective c.Now I updated to 3.2.1 and not able to access settings.selection.max value from Objective c code.Any idea?

**Comment by nayaks2019** [comment]
@mikaoj I noticed now the presentImagePicker function does not have parameter selectLimitReached:^(int maximumSelection) anymore, this was there before.I used this parameter to show how many images are left to pick up to the user on a closure. Is there any specific reason this was removed from presentImagePicker func ?
Or any alternative we have today?
