### ISSUE TITLE
Not getting all Albums

### ISSUE THREAD

**Issue by swapneshp-spaceo** [mikaoj/BSImagePicker#278]
Hi, i have checked your previous issue's related to this and changed the fetchResults in Setting.swift to fetch all the albums which are available in device but not getting the exact output, please check and let me know.

**Comment by mikaoj** [comment]
> but not getting the exact output

What ’output’ are you expecting and what are you getting?

**Comment by swapneshp-spaceo** [comment]
Some weird thing is there, if i am adding this with Pod then its not reflecting the albums but if i add the code manually so all things works fine, and showing the albums as well.
