### ISSUE TITLE
selectLimitReached closure is not getting called anymore

### ISSUE THREAD

**Issue by nayaks2019** [mikaoj/BSImagePicker#281]
I noticed now the presentImagePicker function does not have parameter selectLimitReached:^(int maximumSelection) anymore, this was there before.I used this parameter to show how many images are left to pick up to the user on a closure. Is there any specific reason this was removed from presentImagePicker func ?
Or any alternative we have today?

**Comment by mikaoj** [comment]
I think there is a delegate callback for that. Check out the delegate property.

**Comment by nayaks2019** [comment]
That delegate method does not get called.Tried from ObjC and Swift both.
I made the necessary changes for
### 1.few settings params were not exposed to objC
### 2.MaxSelectionReach closuer was missing
 but when I am trying the push the code for creating Pull request I GET THIS ERROR:
**remote: Permission to mikaoj/BSImagePicker.git denied to SushreeNayak.**
Can you please grant me permission.

**Comment by mikaoj** [comment]
Fork the repo, push a fix to your fork and create a pr to this repo from your fork.

**Comment by nayaks2019** [comment]
Created a pull request.
Please review and let me know if you have question.

I am not able to point my pod file directly to my commit

pod 'BSImagePicker',   :git => 'https://github.com/mikaoj/BSImagePicker.git', : commit `f85875fbd85bcaf35f0644dfaca024a19adef4bf`

getting error:
[!] Error installing BSImagePicker
[!] Failed to download 'BSImagePicker': [!] /usr/bin/git -C /var/folders/zj/x49zsb116lv9drx078115rpc0000gq/T/d20200716-22914-1u7lum5 checkout --quiet f85875fbd85bcaf35f0644dfaca024a19adef4bf

fatal: reference is not a tree: f85875fbd85bcaf35f0644dfaca024a19adef4bf


Sushree Sangita Nayak
Memorial Sloan Kettering Cancer Center
633 3rd Ave, New York, NY 10017
[id:image001.png@01D4E25E.41515740]

**Comment by mikaoj** [comment]
> I am not able to point my pod file directly to my commit

Thats because your commit doesn't exist in my repo. You have to point it towards your own repo.

```
pod 'BSImagePicker',   :git => 'https://github.com/nayaks2019/BSImagePicker.git', : commit `f85875fbd85bcaf35f0644dfaca024a19adef4bf`
```
