### ISSUE TITLE
image quality loss

### ISSUE THREAD

**Issue by muaviya** [mikaoj/BSImagePicker#282]
I downloaded your demo app, get an image from the gallery and display it, the image quality is greatly lost.

**Comment by muaviya** [comment]
my screen - [https://yadi.sk/i/-jsU8pGgR6KjKQ](url)

I this screen from  your demo application, do you see how much the image has lost quality?

**Comment by mikaoj** [comment]
Cool. Can't remember there being an image view in it, so I guess you've made some modifications.
How does your code for fetching the image look like?

**Comment by nagamunireddy** [comment]
Even i am facing the same issue, image quality is poor when i select images from this pod and display it. There is no issue in the image displaying, as the images from camera did not pixelate in the same view that i had displayed.

**Comment by mikaoj** [comment]
> Even i am facing the same issue, image quality is poor when i select images from this pod and display it.

> How does your code for fetching the image look like?

**Comment by muaviya** [comment]
> Cool. Can't remember there being an image view in it, so I guess you've made some modifications.
> How does your code for fetching the image look like?

```
`    @IBAction func showImagePicker(_ sender: UIButton) {
        let imagePicker = ImagePickerController()
        imagePicker.settings.selection.max = 5
        imagePicker.settings.theme.selectionStyle = .numbered
        imagePicker.settings.fetch.assets.supportedMediaTypes = [.image, .video]
        imagePicker.settings.selection.unselectOnReachingMax = true

        let start = Date()
        self.presentImagePicker(imagePicker, select: { (asset) in
            print("Selected: \(asset)")
        }, deselect: { (asset) in
            print("Deselected: \(asset)")
        }, cancel: { (assets) in
            print("Canceled with selections: \(assets)")
        }, finish: { (assets) in
            self.img.image = assets.first!.image
            print("Finished with selections: \(assets)")
        }, completion: {
            let finish = Date()
            print(finish.timeIntervalSince(start))
        })
    }`
```


```
`extension PHAsset {
    var image : UIImage {
        var thumbnail = UIImage()
        let imageManager = PHCachingImageManager()
        imageManager.requestImage(for: self, targetSize: CGSize(width: 100, height: 100), contentMode: .aspectFit, options: nil, resultHandler: { image, _ in
            thumbnail = image!
        })
        return thumbnail
    }
}`
```

**Comment by muaviya** [comment]
fixed the problem using this [link](https://stackoverflow.com/a/42687902/5752412)

my error was in this code: 


```
`extension PHAsset {
    var image : UIImage {
        var thumbnail = UIImage()
        let imageManager = PHCachingImageManager()
        imageManager.requestImage(for: self, targetSize: CGSize(width: 100, height: 100), contentMode: .aspectFit, options: nil, resultHandler: { image, _ in
            thumbnail = image!
        })
        return thumbnail
    }
}`
```

**Comment by mikaoj** [comment]
That is a horrible solution that I wouldn't recommend you using.
First of all it is synchronous and since you don't know if the actual photo is on the phone or in the cloud it can take quite a while to complete i.e probably hanging the entire UI if you are doing it on the main thread.
And since you aren't requesting a specific size I'm assuming it is fetching the entire raw image which can be several megabytes.

The actual error is that you are requesting a 100x100 pixel image but displaying it in a much larger image view, hence it being stretched and pixelated.
Find out how large image you need and request that size instead.
