### ISSUE TITLE
Deselect items on finish

### ISSUE THREAD

**Issue by RomanShyniauski** [mikaoj/BSImagePicker#283]
Hi!
Is there a way to deselect items on finish method? Or just a way to deselect items programmatically?

Use case is the following:
1 - user opens picker and select some items
2 - user clicks done
3 - on finish selected PHAssets are saved locally (e.g. to Documents folder) and the user prompts to delete that items from his library
4 - if user delete them and open picker again it will show that some nonexistent items are selected and can't be deselected

It would be great to see no selected items on reopening ImagePickerController(). So when user opens the same ImagePickerController 2 or more times in the same session he will see screen with no selected items each time.

**Comment by mikaoj** [comment]
Yes. Create a new image picker instance instead of reusing the previous one.

**Comment by RomanShyniauski** [comment]
Yep, using this solution for now
Thought there was any other solution that I missed

Thanks!
