### ISSUE TITLE
There is performance issue while scrolling

### ISSUE THREAD

**Issue by sajib-ghoshInnofied** [mikaoj/BSImagePicker#285]
Thanks for creating this awesome library, this meets my requirement.

But while scrolling through the images I observed that its lagging. It's not scrolling smoothly.
I am using iPhoneX and version - 13.1

Any views on this?

**Comment by mikaoj** [comment]
There is an issue about high memory usage: #271 
Could you do some profiling and see if that is it or if it's something else?

**Comment by sajib-ghoshInnofied** [comment]
Yes. This is related to high memory usage. Please close this issue when you resolve this. It would be very helpful.
