### ISSUE TITLE
iOS 14 permission support

### ISSUE THREAD

**Issue by michelleyin96** [mikaoj/BSImagePicker#288]
Hi team,

Thank you for this awesome library! I'm planning to integrate into my app Tuned but wanted to raise awareness for the iOS 14 new permissions which may affect this library and was wondering if you guys will be planning to add support for it so that there's no issues once the software update becomes available.

Thank you!

**Comment by mikaoj** [comment]
What specific features is it that you want to have support added for?

I've been running it on iOS 14 for a couple of weeks now and it works just fine. Either user gives permission to entire photo library as before or to only selected assets/albums. If the latter a dialog will be presented every now and then asking the user if they still want the app to have access to those assets/albums.

**Comment by ramywagdyrizkalla** [comment]
@mikaoj If the user selected specific images, then the images that the app should have access to are displayed as empty cells like this:

![Limited Image Selection](https://user-images.githubusercontent.com/43375401/93710698-ea93e700-fb48-11ea-96f6-fd7e5eb92e62.png)

**Comment by mikaoj** [comment]
Works for me. Do you use any special settings on the image picker?

**Comment by ramywagdyrizkalla** [comment]
@mikaoj After searching, I found that this issue happens only on simulators and it's working fine on real devices as mentioned in [this opened issue](https://developer.apple.com/forums/thread/657130).

**Comment by mikaoj** [comment]
I did however notice that the animation when long pressing on an image doesn't work in iOS 14.
