### ISSUE TITLE
Picking a video.

### ISSUE THREAD

**Issue by kasyrm** [mikaoj/BSImagePicker#299]
Is there an option to let a user select a video?

Thanks for the library!

**Comment by mikaoj** [comment]
tes :)

**Comment by huy-lv** [comment]
excuse me i have same question, readme page said this support video

**Comment by mikaoj** [comment]
it does

**Comment by huy-lv** [comment]
i tried but no video showed :( that video showed in my Photos app
![image](https://user-images.githubusercontent.com/7688070/95197278-8ab56580-0803-11eb-9a17-ad6ba44bfa1e.png)

**Comment by mikaoj** [comment]
Most of the Settings you can make is contained in Settings.swift - whenever you are wondering how you can change something start by checking it out.

There is also an Examples folder that shows how some of those settings work, have a look at them.

I'm gonna guess that you haven't set ```supportedMediaTypes``` to include videos.

**Comment by huy-lv** [comment]
yes, we can edit Settings.swift to add support media type. So we have to change lib source code, haven't we? I think this is not good approach

**Comment by kasyrm** [comment]
No we don't. The source code for media types is in Settings.swift. It's your business to use it properly in your code.

**Comment by mikaoj** [comment]
Dude. No.

Code from the Example folder that I asked you to have a look at.
> So we have to change lib source code, haven't we?

No. See example.

```swift

import BSImagePicker
        let imagePicker = ImagePickerController()
        imagePicker.settings.selection.max = 5
        imagePicker.settings.theme.selectionStyle = .numbered
        imagePicker.settings.fetch.assets.supportedMediaTypes = [.image, .video]
        imagePicker.settings.selection.unselectOnReachingMax = true
```

**Comment by huy-lv** [comment]
Yeah thank, i understood how it work, i think you should include this snippet to readme page :D

**Comment by mikaoj** [comment]
>  i think you should include this snippet to readme page

You mean like how I included an example of how to fetch an image for an asset which you still created an issue about?
It doesn't matter how much I put into the README, documentation or Examples if you aren't reading them. :)

**Comment by huy-lv** [comment]
I'm sorry for not reading the example, but i have read README and search in all issues and still can't find out how to pick a video. Your readme doesn't mention about the Example folder. I think you should tell user how to enable video picking, or tell them about the Example folder (in README).
