### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by mikaoj** [mikaoj/BSImagePicker#30]
Video support got dropped for 1.0.
Reimplement it

**Comment by onato** [comment]
I need video and would be happy to help out? Anything I should know before creating a pull request?

**Comment by amos-yau** [comment]
@onato did you added, i would like to pick video too!

**Comment by onato** [comment]
Not with this library. I switched to https://github.com/hyperoslo/ImagePicker and added there.

**Comment by dfujiwara** [comment]
@mikaoj, I am going to take a look at this, but is there anything I should be aware of?
