### ISSUE TITLE
Change vc modal presentation style.

### ISSUE THREAD

**Issue by ElrB** [mikaoj/BSImagePicker#305]
Hi, since swift's default vc modal presentation style change to automatic, how can I set the image picker to present in fullscreen, currently presents in page sheet, and am unable to select specific photo albums, since that property I think is on nav bar. Thanks.

**Comment by ElrB** [comment]
Any help please? I tried to check in the vc settings, but couldn't find it. Thanks in advance.

**Comment by mikaoj** [comment]
> Hi, since swift's default vc modal presentation style change to automatic

Swift hasn't a default setting for presentation style.
iOS however changed default for iOS 13.

And you would change it for the image picker just as you would with any other view controller you want to present in a modal.
```
imagePicker.modalPresentationStyle = .fullScreen
```

> and am unable to select specific photo albums, since that property I think is on nav bar.

Don't know what you mean here.

**Comment by ElrB** [comment]
Thank you. Its now presenting in fullscreen.
