### ISSUE TITLE
Album selection option not appearing on image picker navigation bar.

### ISSUE THREAD

**Issue by ElrB** [mikaoj/BSImagePicker#308]
Hi, I just wanted to know how to show the option of album selection on navigation bar of image picker. Currently there's only "Cancel" and "Done". Here is my image picker settings: 

self.itemPickerViewController.modalPresentationStyle = .fullScreen
        
        self.itemPickerViewController.settings.selection.max = 8
        self.itemPickerViewController.settings.theme.selectionStyle = .numbered
        self.itemPickerViewController.settings.fetch.assets.supportedMediaTypes = [.image, .video]
        self.itemPickerViewController.settings.selection.unselectOnReachingMax = true
        
        self.itemPickerViewController.settings.theme.albumTitleAttributes = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 18),NSAttributedString.Key.foregroundColor: UIColor.black]

Thanks.

**Comment by bivant** [comment]
Like [this](https://github.com/mikaoj/BSImagePicker/issues/290#issuecomment-670531194)?
