### ISSUE TITLE
Take picture

### ISSUE THREAD

**Issue by mikaoj** [mikaoj/BSImagePicker#31]
Add support for taking new pictures.
Make it an optional subspec?

**Comment by seapy** [comment]
+1 i want this feature too

**Comment by mikaoj** [comment]
The stuff I'm working on now (see WIP pull request) will make camera integration easier to implement :)

**Comment by mikaoj** [comment]
I've began implementation of this feature.
You can follow the progress here: https://github.com/mikaoj/BSImagePicker/pull/34
