### ISSUE TITLE
Image picker not displaying albums selection.

### ISSUE THREAD

**Issue by HoffofAllTrades** [mikaoj/BSImagePicker#310]
Think the title pretty much says it all.

**Comment by HoffofAllTrades** [comment]
oh also, think I should note this is latest iOS 14

**Comment by mikaoj** [comment]
I think a search says even more

https://github.com/mikaoj/BSImagePicker/issues/308
https://github.com/mikaoj/BSImagePicker/issues/290
https://github.com/mikaoj/BSImagePicker/issues/278
https://github.com/mikaoj/BSImagePicker/issues/262

**Comment by HoffofAllTrades** [comment]
Thanks. I downloaded the example project, none of the prepackaged examples showed this, so should probably add that as one of the examples.

**Comment by mikaoj** [comment]
Sounds good, feel free to open a PR with that :)
