### ISSUE TITLE
Album button not showing on ios 13.x

### ISSUE THREAD

**Issue by mandic1987** [mikaoj/BSImagePicker#321]
Hello,

I have problem with album button... Works on ios 14.x, but not on ios 13.x. This is my code:

let imagePicker = ImagePickerController()
imagePicker.settings.fetch.assets.supportedMediaTypes = [.image, .video]
imagePicker.settings.selection.max = 10
imagePicker.settings.selection.unselectOnReachingMax = false
        
let options = imagePicker.settings.fetch.album.options
imagePicker.settings.fetch.album.fetchResults = [PHAssetCollection.fetchAssetCollections(with: .smartAlbum, subtype: .smartAlbumUserLibrary, options: options), PHAssetCollection.fetchAssetCollections(with: .album, subtype: .albumRegular, options: options)]

What could be the problem?

Thanks

**Comment by mikaoj** [comment]
It is only visible if there actually is multiple albums/collections on the device.
Could it be that you only have 1 on the iOS 13 device?

**Comment by mandic1987** [comment]
Yes,thats right... I just test it...

Problem solved...

Thank you very much :)

**Comment by lilyxxlin637** [comment]
I did something similar but with 
"multiImgPicker.settings.fetch.album.fetchResults = [PHAssetCollection.fetchAssetCollections(with: .smartAlbum, subtype: .any, options: options)]" 
But it does not display the album button either. I do have images in my smart albums like "favorite" and the fetch returns a count of 14 albums. 
could you provide some guide on what else to try?
