### ISSUE TITLE
[Feature Request] Indicating previously selected assets

### ISSUE THREAD

**Issue by koczka** [mikaoj/BSImagePicker#322]
Hey,

I've been working on a project, and my use case would need to show the user the previously assets if they open the picker multiple times. I've been trying to implement this on an own fork, but no luck so far.

Any ideas?

Thanks!

**Comment by mikaoj** [comment]
Instead of creating a new picker every time keep a reference to a single picker that you present

**Comment by koczka** [comment]
Sorry, I wasn't precise enough.

I need a way to show the previously selected assets, without them affecting the selection. Kind of like an overlay.

**Comment by mikaoj** [comment]
Did you find a solution?

**Comment by koczka** [comment]
Yeah, I did.

I created an exposed variable of type [PHAsset], which holds the previously selected assets, provided from outside the picker.
And I modified the datasource delegate to configure the cells when I open the picker.

I implemented this image picker in an Ionic Capacitor Plugin, that I use for my project.
