### ISSUE TITLE
BSImagePicker.framework does not contain a bundle executable

### ISSUE THREAD

**Issue by jalalhaider** [mikaoj/BSImagePicker#354]
Unexpected CFBundleExecutable Key. The bundle at 'Payload/Runner.app/Frameworks/BSImagePicker.framework/BSImagePicker.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue. (ID: 3f972027-ecc4-40
<img width="728" alt="Screenshot 2023-11-03 at 1 04 06 PM" src="https://github.com/mikaoj/BSImagePicker/assets/18090876/68eaee0c-a59e-48e7-9a6b-1b315001c752">
64-a60e-8623a5e12f43)

**Comment by mikaoj** [comment]
Try using branch bugfix/info_plist and see if that resolves it

**Comment by jalalhaider** [comment]
IT worked thanks ! 

I changed CFBundlePackageType value BNDL under pod files in BSImagePicker info.plist and it worked
<img width="1114" alt="Screenshot 2023-11-03 at 4 37 51 PM" src="https://github.com/mikaoj/BSImagePicker/assets/18090876/7b367d31-ecd0-4ad8-837f-25fdf9f04c65">

<img width="759" alt="Screenshot 2023-11-03 at 4 37 04 PM" src="https://github.com/mikaoj/BSImagePicker/assets/18090876/f7a51157-1026-4a1d-ab02-13442923c427">
