### ISSUE TITLE
Describing use of required reason API

### ISSUE THREAD

**Issue by hsingh-texada** [mikaoj/BSImagePicker#359]
Starting spring of 2024, Apple will be mandating the use of xcprivacy file to be included by all the libraries.
The relevant Apple requirement/documentation is as follows:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Can you please provide timelines on when this would be resolved, as it will directly impact our AppStore submissions.

The API in question: 

[File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393)
The following APIs for accessing file timestamps require reasons for use. Use the string NSPrivacyAccessedAPICategoryFileTimestamp as the value for the NSPrivacyAccessedAPIType key in your NSPrivacyAccessedAPITypes dictionary.

[creationDate](https://developer.apple.com/documentation/foundation/fileattributekey/1418187-creationdate)

The code snippet:
https://github.com/mikaoj/BSImagePicker/blob/7afbaa1daf882b9f90e8e4a42f7b102f9d589245/Sources/Scene/Preview/PreviewTitleBuilder.swift#L37

**Comment by hsingh-texada** [comment]
@mikaoj I created a PR to add the info. Would you be able to review and if all looks good, merged and tag it. Thanks.

**Comment by hsingh-texada** [comment]
@mikaoj  Would you be able to tag the change, so that SPM can pick it up.

**Comment by hsingh-texada** [comment]
@mikaoj Following up on the tagging request.

**Comment by mikaoj** [comment]
Yes I'll tag a new version. And update the cocoapod.
In the meantime if it's urgent you can use a specific branch of even commit. You don't _need_ a tag for SPM to pick it up.

**Comment by mikaoj** [comment]
New version tagged. Thanks for contributing @hsingh-texada !
