### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by tuncayforma38** [mikaoj/BSImagePicker#363]
Hello, I am experiencing the same problem as in this issue #362  in my project. maine has been merged but I did not see a new release. Do you have any plans for release?

**Comment by mikaoj** [comment]
You can always use a specific branch or commit hash instead of a version.
But yes I'll release a new version soon.

**Comment by mikaoj** [comment]
Tagged 3.3.3

**Comment by tuncayforma38** [comment]
Thank you. enjoy your work :)
