### ISSUE TITLE
how to change the cancelButton title?

### ISSUE THREAD

**Issue by train860** [mikaoj/BSImagePicker#39]
I want to change the cancelButton title from "Cancel" to another one!
is there some ways to change it?
thank you!

**Comment by mikaoj** [comment]
Yes.

The system should localize it to whatever cancel is in your language, as it is UIBarButtonSystemItemCancel.
If you aren't happy with that you can do some voodoo on it to change the title. I do it with the done button to add the count. 
Check out a function named something like updateDoneButton in PhotosViewController for an example.

I don't have my computer with me today, so this is the best answer I can give at the moment, I hope it helps! :)
