### ISSUE TITLE
can't install latest version w/ latest CocoaPods

### ISSUE THREAD

**Issue by taberrr** [mikaoj/BSImagePicker#41]
Hey there, I'm trying to install this w/ CocoaPods 0.38.2 but I'm getting:

    [!] Unable to satisfy the following requirements:
    
    - BSImagePicker (= 1.4.0) required by Podfile

Not sure if this is an issue with the BSImagePicker .podspec or something to do with their new Cocoapods Trunk stuff: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

*Update:* if I completely remove any versioning in the Podfile, it seems like an older version of BSImage is installed, one that uses ALAssets instead of PHAssets.

*Update 2:* as a workaround I downgraded CocoaPods to 0.37.2

**Comment by nishantdongare** [comment]
update CocoaPods has worked for me

**Comment by mlb5000** [comment]
@taberrr The error message with the latest Cocoapods is more descriptive, at least in my case:

    [!] Unable to satisfy the following requirements:
    
    - `BSImagePicker (~> 1.4)` required by `Podfile`
    
    Specs satisfying the `BSImagePicker (~> 1.4)` dependency were found, but they required a higher minimum deployment target.


You either need to have you minimum target set to 8.0, or you need to be OK with running 0.7, which is the last version to support iOS 7.

**Comment by taberrr** [comment]
@mlb5000 ah great, thanks!
