### ISSUE TITLE
No Selection and browsing form preview

### ISSUE THREAD

**Issue by GPicora** [mikaoj/BSImagePicker#45]
On the demo on CocoaControls, there is a very interesting feature which is why I choose your great component, really its very good! :).  

The feature Im talking about is the posibility to select images while previewing them.  Also while on preview is supposed to be possible to navigate thru the images in the library, but now it seems those 2 things are gone or I have something very wrongly configured... :( 

Thx
G.

**Comment by GPicora** [comment]
I forgot to mention that selectionFillColor seems to do nothing,   If I understand correctly this is the color for the circle at the bottom right edge?  No matter what color I set it just remains blue.

**Comment by mikaoj** [comment]
Thanks for reporting the issue, I have fixed the selection color bug with 1.4.2 :)

Browsing from preview was a feature that was dropped with the 1.0 release. Perhaps it will make it's way back in the future :)
