### ISSUE TITLE
PHAsset.fetchAssetsInAssetCollection is being called twice

### ISSUE THREAD

**Issue by markkrenek** [mikaoj/BSImagePicker#50]
In AlbumCellFactory.cellForIndexPath, PHAsset.fetchAssetsInAssetCollection is being called twice which causes a huge hit on performance. The first call appears to be a mistake because it ignores the results.

**Comment by mikaoj** [comment]
You're right, nice catch! :+1:

**Comment by mikaoj** [comment]
Pushed out 1.4.3 which removes the duplicate asset fetch, thanks for reporting it! :)
