### ISSUE TITLE
UICollectionView resets everything on every asset change

### ISSUE THREAD

**Issue by Velociround** [mikaoj/BSImagePicker#51]
Every time assets change, the UICollectionView is reset and goes back to top position.

This is a problem in several scenarios:
- If I try to cache assets when the user selects it, after each asset cache is finished downloading, the scrollView will reset to top and the user will lose its place in the middle of selecting assets
- If the user's phone hasn't finished downloading a thumbnail for every picture in his gallery, every time a thumbnail finishes downloading, the scrollView will reset to the top.

I actually wanted to create a pull request with this fixed (and also with video support) but I'm on a really tight schedule and management has already told me to scrap that and stop caching images (workaround for first scenario), and hope the user has already all its photos' thumbnails downloaded... which is not my case at all (as a user), so it's really making me unable to use BSImagePicker at all.

**Comment by mikaoj** [comment]
Are you fetching assets from iCloud?

**Comment by Velociround** [comment]
Yes, I am. I have PHImageRequestOptions.networkAccessAllowed = YES;

But the problem happens even BSImagePicker tries to fetch from iCloud too.

I have iCloud Photo Library enabled.

**Comment by mikaoj** [comment]
Cool, never tried it with iCloud :)
But thanks for reporting it, I'll have a look at it when I get the time...or if anyone else beats me to it :)

**Comment by mikaoj** [comment]
Thanks for reporting it!

**Comment by Velociround** [comment]
I think it's probably easy to fix, too; I'm guessing you're probably using collectionView.reloadData() when you get the assets changed notification; changing it to collectionView.reloadRows(rows atIndexPaths:indexPaths) should do the trick.

I can help you testing when you get the time if you want. :)

I'm typing on my phone by the way, I'm not sure this is exactly the name of the method but it's something like that.

**Comment by mikaoj** [comment]
It should only be doing a complete reloadData if the change result has the incremental change flag set to false. Otherwise it should delete, insert and reload only what has changed. SHOULD being the keyword here ;)
