### ISSUE TITLE
Deselect pragmatically an asset.

### ISSUE THREAD

**Issue by GPicora** [mikaoj/BSImagePicker#52]
Hello,

I know this is not a bug, but I just want to ask: 

Is there a way to deselect pragmatically an asset from the current selections?  I haven't figure it out how. :( 

Thanks

G.

**Comment by mikaoj** [comment]
Nope :)
Why would you want to do that?

**Comment by mikaoj** [comment]
I wanted to know why as to see if it is an edge case or something that I should implement ^^

**Comment by GPicora** [comment]
Hello, sorry for the late reply.
Basically in my app after choosing the assets im showing a component i did to preview and edit the seected images, there is also a delete button there. So if a user chose 5 and in my component decided to dont include one but instead another one, normally he would just delete the one he doesnt want and hide my component (which based on my app arch will display the imagepicker again), but as u can guess even the user deleted one image from my edit controller, if coming back he will see it still selected, which is weird, not critical though. ;)

**Comment by AitorAlgorta** [comment]
I also need this feature and I think it is really important. You should have the option of select and deselect pragmatically.

**Comment by sdevaz** [comment]
@mikaoj I would appreciate this functionality because I want to reject (i.e. deselect) assets that do not meet a specific set of requirements (e.g. image dimensions, image file size.)

For now I think I'll compromise by handling this in the `finish` closure - which isn't an ideal user experience since they only find out after having already selected their desired assets.

Thanks

**Comment by at-duytang** [comment]
@mikaoj I also need this feature because when the user selects an image is an invalid format, I don't user must deselect this image and I don't want to `Done` button is active. Thanks.

**Comment by mikaoj** [comment]
@sdevaz @at-duytang Sounds like you should look into setting up a PHFetchOption with a predicate that filters out invalid formats, sizes, etc.

Not showing the images in the first place sound like a better UX then showing them but not allowing them to be selected :) 

But I'll keep this in mind in future updates

**Comment by at-duytang** [comment]
@mikaoj Yep, Thanks for your response. I also think about this, I will try. Thanks.

**Comment by chuckfinca** [comment]
Use case:

I'm currently trying to pair BSImagePicker with [CropViewController](https://github.com/TimOliver/TOCropViewController) such that each time an asset is selected it is immediately cropped, then the user returns to the picker and continues.

If the user clicks cancel in the cropper I would like to deselect the asset in BSImagePicker. I.E. I don't what to have an un-cropped image selected.
