### ISSUE TITLE
Camera icon when takePhotos is true

### ISSUE THREAD

**Issue by gluecode** [mikaoj/BSImagePicker#54]
Hi,
It would be great if the camera icon is customizable when takePhotos is true. The blue color is not convenient for some people challenged with bad vision.

Thank you very much.

Sunil

**Comment by mikaoj** [comment]
The icon is actually black. So when the icon is displayed as blue, you are setting the color on it :)
You can change this by setting tintColor

**Comment by gluecode** [comment]
Thank you :-) 
My storyboard tintColor is not blue. The view tintColor is default to storyboard. So I am not sure which tintColor to set.

**Comment by gluecode** [comment]
Ah! No worries got it.

`vc.view.tintColor = UIColor.redColor()`

**Comment by Hamza-Brainplow** [comment]
I'm using BSImagePicker for selecting multiple images from gallery and shows the images in a collection view. I want to know that how can we select image through camera using BSImagePicker?
