### ISSUE TITLE
Size of camera icon when takePhotos is true

### ISSUE THREAD

**Issue by gluecode** [mikaoj/BSImagePicker#55]
Hi,
It would be great if the camera icon size can be changed (or passed a new image) when takePhotos is true. The icon is a small as per user feedback from visually challenged testers.

Thank you very much again :-) 

Sunil

**Comment by mikaoj** [comment]
Makes sense, I will look into adding it in a future release. I can't promise when that will be, so if you want it now I would be happy to look at a pull-request fixing it :)

**Comment by gluecode** [comment]
Thank you for all you do. I will give it a try. My skills are limited and not as good as your's :-)

**Comment by mikaoj** [comment]
If you update to 2.1.0 you will have a takePhotoIcon property that you can set :)

**Comment by gluecode** [comment]
Oh, thank you! I just tried this and it works perfectly! With a lot of thanks.

- Sunil
