### ISSUE TITLE
Picker always leaves out 1 photo when selecting from album

### ISSUE THREAD

**Issue by awhitman92** [mikaoj/BSImagePicker#56]
When you go into an album you have on your device 1 photo is always missing. If you only have 1 photo in the album there is none present. If you have 4, there is 3 present.

**Comment by mikaoj** [comment]
Wow, I'll look into it. Thanks for reporting it!

**Comment by mikaoj** [comment]
Found it, fixed it. It was a bug in a dependency (BSGridCollectionViewLayout).
So if you just do a pod update it should pull in version 1.0.1 of BSGridCollectionViewLayout with the fix
