### ISSUE TITLE
Remove final from BSImagePickerViewController

### ISSUE THREAD

**Issue by marcelofabri** [mikaoj/BSImagePicker#62]
I want to override `preferredStatusBarStyle()` on `BSImagePickerViewController`, but can't do that with a subclass, because the class is `final`.

Instead of predicting all desired functionalities, IMO `BSImagePickerViewController` shouldn't be final, so developers could customize it.

**Comment by mikaoj** [comment]
I'm looking forward to your pull request which changes it to final :)
