### ISSUE TITLE
How to pick only videos?

### ISSUE THREAD

**Issue by KimCrab** [mikaoj/BSImagePicker#65]
I can't see how to pick videos or only videos.

Is it not supported? or I'm missing something?

**Comment by mikaoj** [comment]
It is not supported. But I should probably add it some day...

**Comment by mikaoj** [comment]
Duplicate #30

**Comment by sparshme5** [comment]
Do we have video picker support for this library?

**Comment by sreeni-wk** [comment]
How can we disable videos while image picker appears? Currently it will show photos and videos.
