### ISSUE TITLE
Can't camera button

### ISSUE THREAD

**Issue by Ying1986** [mikaoj/BSImagePicker#68]
I can't see camera button sometimes.

https://www.dropbox.com/s/3bmdgrzp3s56rxd/Camera%20button.mp4?dl=0#

and what is the correct **BSImagePicker**?

Another path: https://github.com/asefnoor/BSImagePicker

**Comment by mikaoj** [comment]
Thanks for reporting it! I'll have a look at it when I get the time.

This is the 'correct' BSImagePicker. The others (there are 83 of them) are whats called forks, and sometimes they contribute back to this repo. https://guides.github.com/activities/forking/

**Comment by Ying1986** [comment]
@mikaoj 

I'm using your library in my project, and my client wants to fix this issue asap.
Can you help me now?
Thank you.

**Comment by mikaoj** [comment]
Could you show me your code for creating, setting up and presenting the image picker?

I’m Joakim Gyllström and I approve this message


På 21 mars 2016 till 11:03:46, Ying1986 (notifications@github.com<mailto:notifications@github.com>) skrev:

@mikaoj<https://github.com/mikaoj>

I'm using your library in my project, and my client wants to fix this issue asap.
Can you help me now?
Thank you.

**Comment by Ying1986** [comment]
I have used your code in objective-c:
`    BSImagePickerViewController* vc = [[BSImagePickerViewController alloc] initWithDefaultSelections: nil];
   
    vc.maxNumberOfSelections = 5;

    UIImage *cameraImage = [UIImage imageWithIcon:@"fa-camera" backgroundColor:[UIColor clearColor] iconColor:[UIColor darkGrayColor] fontSize: 30];
    
    vc.takePhotoIcon = cameraImage;
    vc.takePhotos = true;

    vc.selectionFillColor = [UIColor grayColor];
    vc.selectionStrokeColor = [UIColor yellowColor];
    vc.selectionShadowColor = [UIColor redColor];
    
    [self bs_presentImagePickerController: vc animated:YES select:^(PHAsset * _Nonnull asset) {
        
    } deselect:^(PHAsset * _Nonnull asset) {
        
    } cancel:^(NSArray<PHAsset *> * _Nonnull asset) {
        
    } finish:^(NSArray<PHAsset *> * _Nonnull assets) {
    } completion:^{
        
    }];`

**Comment by mikaoj** [comment]
Thanks! Could you try it without setting you own custom camera icon?

**Comment by Ying1986** [comment]
yes, but I need own icon, because this library use heart icon as camera,

I think camera icon is not the reason of this issue.

**Comment by mikaoj** [comment]
I understand that, but I'm trying to pinpoint the problem so that I can fix it later. There more you can help me with that the quicker I can apply my limited time to the right area in the code :)

Could you try removing those lines and see if it helps?
Or at least not use the category function for creating an image with icon, background color, icon color and font size. And use the plain UIImage(named: "chat") instead.

This is not intended as a permanent fix, but only to find out where the problem actually is.

**Comment by mikaoj** [comment]
And no, the default is not an heart. If you don't set the camera at all the default will actually be a camera :)

The heart is only in the example to show how you actually set it if you don't like the default.

**Comment by mikaoj** [comment]
Any update on this?
