### ISSUE TITLE
Can't build with XCode 7.3, Swift 2.2, Cocoapod 1.0.0.beta.6, BSImagePicker 2.2.0

### ISSUE THREAD

**Issue by Zigzag968** [mikaoj/BSImagePicker#69]
i have an issue when building my app since i have updated Xcode from 7.2 to 7.3

I'm using :
- BSImagePicker (2.2.0):
    - BSGridCollectionViewLayout (~> 1.0)
    - UIImageViewModeScaleAspect (~> 1.3)

This is what xcode says :

CpResource /Users/alexandreguibert/Library/Developer/Xcode/DerivedData/Evaneos-detujkeddycfbxdybrazrjyowroh/Build/Products/Dev-iphonesimulator/BSImagePicker/BSImagePicker.bundle /Users/alexandreguibert/Library/Developer/Xcode/DerivedData/Evaneos-detujkeddycfbxdybrazrjyowroh/Build/Products/Dev-iphonesimulator/BSImagePicker/BSImagePicker.framework/BSImagePicker.bundle
    cd /Users/alexandreguibert/Documents/Apps/evaneos/Pods
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -strip-debug-symbols -strip-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -resolve-src-symlinks /Users/alexandreguibert/Library/Developer/Xcode/DerivedData/Evaneos-detujkeddycfbxdybrazrjyowroh/Build/Products/Dev-iphonesimulator/BSImagePicker/BSImagePicker.bundle /Users/alexandreguibert/Library/Developer/Xcode/DerivedData/Evaneos-detujkeddycfbxdybrazrjyowroh/Build/Products/Dev-iphonesimulator/BSImagePicker/BSImagePicker.framework

error: /Users/alexandreguibert/Library/Developer/Xcode/DerivedData/Evaneos-detujkeddycfbxdybrazrjyowroh/Build/Products/Dev-iphonesimulator/BSImagePicker/BSImagePicker.bundle: No such file or directory

**Comment by mikaoj** [comment]
CocoaPods 0.39 and Xcode 7.3 works for me. Haven't had the time to test any of the CocoaPods betas yet.

**Comment by Querschlag** [comment]
That's a bug in cocoapods beta6 -> https://github.com/CocoaPods/CocoaPods/issues/5034
Just install beta5 with `gem install cocoapods -v 1.0.0.beta.5`
