### ISSUE TITLE
Cannot use this with xcode 7.3

### ISSUE THREAD

**Issue by rujoota** [mikaoj/BSImagePicker#71]
I am using cocoa pods to get this in my project but I fail to build my project because I am getting 'build error' in PreviewViewController and PhotosViewController. The error is coming because of usage of action: #selector syntax

**Comment by mikaoj** [comment]
Are you sure you are using 7.3? #selector is a Swift 2.2 feature that you got with Xcode 7.3

**Comment by rujoota** [comment]
Yes, I am using xcode Version 7.3 beta 3 (7D141l)

**Comment by mikaoj** [comment]
Beta? Upgrade to the release

**Comment by mikaoj** [comment]
Did that work?

**Comment by rujoota** [comment]
Yes it works except now it throws following exception after adding pod on runtime:

dyld: Library not loaded: @rpath/BSImagePicker.framework/BSImagePicker
  Referenced from: /Users/username/Library/Developer/CoreSimulator/Devices/B094A6D0-F455-48D1-A3A7-7A85FF3A483A/data/Containers/Bundle/Application/6F46D651-57E0-43BC-ABB8-C7E86081B0D1/MyProj.app/MyProj
  Reason: image not found

**Comment by mikaoj** [comment]
Which cocoapods version are you using?

**Comment by rujoota** [comment]
I am using CocoaPods 1.0.0.beta.5(desktop app)

**Comment by mikaoj** [comment]
Beta? Downgrade to 0.39 or atleast upgrade to the latest beta, which I think is 8.

**Comment by rujoota** [comment]
Somehow when I used cocoapods command line tools it worked! Thanks.
