### ISSUE TITLE
Selecting photos then minimizing and deleting them does not remove them from selection

### ISSUE THREAD

**Issue by sherifnada** [mikaoj/BSImagePicker#72]
Hi there! 
Found a fringe case that you might want to know about:
1. Call bs_presentImagePickerController, this will bring up the image picker
2. Once in the BSImagePicker, select a photo
3. Tap the home button, go to photo library. 
4. Delete the photo from the phone by first deleting it from its album, then deleting it from "recently deleted"
5. Go back to BSImagePicker
6. The right nav button still says "Done(1)", and on clicking done, returns the image.

If a user were to fetch the image from PHImageManager based on the asset, this might cause a crash. 

Again, fringe case, but thought you might want to know. Thanks for maintaining this awesome library! :)

**Comment by mikaoj** [comment]
Yeah, that is a case it haven't handled. Thanks for bringing my attention to it! 👍

**Comment by telip007** [comment]
Any progress on this topic ? Or did you, @sherifnada, find a workaround ?
