### ISSUE TITLE
Crash? while using the assets passed back. 

### ISSUE THREAD

**Issue by alexliubj** [mikaoj/BSImagePicker#73]
`let vc = PhotosViewController(fetchResults: self.fetchResults,`
                                      `defaultSelections: self.defaultSelections,`
                                   `settings: self.settings)`
 `vc.finishClosure = { (assets: [PHAsset]) in`

```
      `  for (index, asset) in assets.enumerate()
        {
            let manager = PHImageManager.defaultManager()
            manager.requestImageForAsset(asset, targetSize: CGSize(width: 100.0, height: 100.0), contentMode: .AspectFit, options: nil, resultHandler: {(result, info)->Void in
                // crash here sometimes while I'm trying to use this result, and it say can't unwrap it.
            })
        }
    }`
```

**Comment by sherifnada** [comment]
You should inspect the `info` object to make sure the image request finished without errors.[ From ImageResultInfoKeys documentation](https://developer.apple.com/library/ios/documentation/Photos/Reference/PHImageManager_Class/#//apple_ref/doc/constant_group/Image_Result_Info_Keys): 

> PHImageErrorKey
An error that occurred when Photos attempted to load the image. (NSError)
Photos **provides an error object for this key if it cannot provide an image** for your handler block’s result parameter. Examine the error object for information about the cause of the error.

So before you attempt to unwrap the result, you should check if there was no error fetching the image.

**Comment by alexliubj** [comment]
@sherifnada  thanks for your quick reply, I will test it laster and keep updating. 

Thanks,

**Comment by alexliubj** [comment]
Was there something wrong with it?
I had two images and the following are the information I printed for 'info'

Optional([PHImageResultIsDegradedKey: 0, PHImageResultWantedImageFormatKey: 4031, PHImageResultRequestIDKey: 9, PHImageFileOrientationKey: 0, PHImageResultDeliveredImageFormatKey: 4031])

Optional([PHImageResultIsDegradedKey: 0, PHImageResultWantedImageFormatKey: 4031, PHImageResultRequestIDKey: 10, PHImageFileOrientationKey: 0, PHImageResultDeliveredImageFormatKey: 4031])
