### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by paradoxally** [mikaoj/BSImagePicker#77]
It would be great if this project were eventually updated to support Swift 3, now that it has been [officially announced by Apple](https://developer.apple.com/swift/blog/#article-36). 

I have it working with Swift 2.3, but when it comes to 3 there are a lot of source changes that break it.

**Comment by mikaoj** [comment]
Yeah, I'll look into it 🤖

I’m Joakim Gyllström and I approve this message

På 24 juni 2016 till 20:15:47, Nino (notifications@github.com<mailto:notifications@github.com>) skrev:

It would be great if this project were eventually updated to support Swift 3, now that it has been officially announced by Apple<https://developer.apple.com/swift/blog/#article-36>.

I have it working with Swift 2.3, but when it comes to 3 there are a lot of source changes that break it.

**Comment by ekurutepe** [comment]
@mikaoj I have a working Swift 3 version in my fork. I can send a pull request but it probably makes more sense if you create swift-3 branch first.

**Comment by mikaoj** [comment]
Great, I'll hook you up with a swift 3 branch.

I started converting stuff to swift 3/iOS 10 a couple of weeks ago, but ran into som issues with the collection view layout which I assumed was bugs in iOS 10, so decided to wait a couple of betas before giving it a try again ;)

**Comment by mikaoj** [comment]
There you go, swift3 🤓

**Comment by adhiravishankar** [comment]
Now that Xcode 8 has been released, will there be movement on this?

**Comment by ekurutepe** [comment]
@adhiravishankar sorry this dropped off my radar. I'll see if I still have that swift3.0 port somewhere and send a PR.

**Comment by adhiravishankar** [comment]
Check it with the current Xcode to make sure everything works. Sometimes, I find minor things have changed between even the GM version and the current release.

**Comment by mikaoj** [comment]
Converted the the code to Swift 3 today (haven't pushed it yet)...but ran into some issues with the generated obj-c header. But I'm getting there :)

**Comment by paradoxally** [comment]
Does the `3_0_0` branch contain a fully working version at this point? I'm asking because I cloned and compiled the example and it runs, but the checkmark image doesn't appear when selecting photos in the simulator (iOS 10, iPhone 7). May be just a bug, not sure.

Thanks.

**Comment by berabhavin** [comment]
i have getting many issue in swift 3.

**Comment by mikaoj** [comment]
@paradoxally 3_0_0 is not a fully working version, don´t use that branch :)

**Comment by gwigz** [comment]
I got @felipecarreramo's fork working, might be the same for the `3_0_0` branch, but I can't use that due to the missing podspec.

Before you read on; my apologies if this isn't a good idea, I have never wrote Objective-C before. 😓 

Anyway, it seems to compile and function for my uses if you replace line `119` of `BSImagePicker-Swift.h`

```objc
- (nonnull instancetype)initWithFetchResults:(NSArray<PHFetchResult<id> *> * _Nonnull)fetchResults;
```

With the following, which I gathered from [the photos changes page, here.](
https://developer.apple.com/library/content/releasenotes/General/iOS90APIDiffs/Objective-C/Photos.html)

```objc
- (nonnull instancetype)initWithFetchResults:(NSArray<PHFetchResult *> * _Nonnull)fetchResults;
```

With `@class PHFetchResult` added to the files class defines.

**Comment by dernise** [comment]
I'd really like to update my project to swift 3, would that be possible to have a swift 3 version ?

**Comment by mikaoj** [comment]
I'm having issues with cocoapods not letting me do a pod lib lint. So I can't push a swift3 version to the spec repo.
I have created a swift3 branch which also contains a couple of iOS 10 bugfixes. You could direct your Podfile to use that branch until I've managed to get cocoapods working.

pod 'BSImagePicker', :git => 'https://github.com/mikaoj/BSImagePicker.git', :branch => 'swift3'
https://guides.cocoapods.org/syntax/podfile.html#pod

**Comment by mikaoj** [comment]
Pushed 2.5.0 which is in Swift 3

**Comment by tzdesign** [comment]
Why is that closed? I testet it on iOS10 iPhone7 and iPad Air2 and it is not working.
It's crashing right when the is trying to come up.

**Comment by sanjukhunt** [comment]
Hello @mikaoj  i am still unable to update pod for swift 3. can you please send me full path for swift 3.0 support 

I am using this branch 
pod 'BSImagePicker', :git => 'https://github.com/mikaoj/BSImagePicker.git', :branch => '3_0_0'

but facing bellow error while pod install 
Unable to find a specification for 'BSImagePicker'.

[!] Unable to load a podspec from `BSImagePicker.podspec`, skipping:

Invalid podspec file at path `/var/folders/1c/466kpt9n72v1smxv8h2lntxc0000gn/T/d20161116-2341-1xmoltx/BSImagePicker.podspec`.

Please help me 
Thanks a lot

**Comment by dernise** [comment]
@sanjukhunt Please use the master branch, it is compatible with swift 3. The 3_0_0, as I understood, is an experimental branch.

**Comment by mikaoj** [comment]
What @dernise said. The latest version (2.5.1) should be Swift 3 compatible
