### ISSUE TITLE
UIButton extension animation Error

### ISSUE THREAD

**Issue by Geddy05** [mikaoj/BSImagePicker#78]
When i create a BSImagePickerViewController with animation false.
I still see animation after taking a picture. I found the issue in UIButton Extension where the UIView.setAnimationsEnabled(true) will be set too true. 
if you change the function like this you fixed the issue 

```
func bs_setTitleWithoutAnimation(title: String?, forState state: UIControlState) {
        // Disable/enable animations
        let animationEnabled = UIView.areAnimationsEnabled()
        UIView.setAnimationsEnabled(false)
        
        // Set title without the default animation
        self.setTitle(title, forState: state)
        self.layoutIfNeeded()
        
        // Enable animations
        UIView.setAnimationsEnabled(animationEnabled)
    }
```

**Comment by mikaoj** [comment]
Cool, I'll look into it later this summer when i hopefully will have some free time.
If you want to submit a pullrequest with the fix I'll be happy to look at it :)
