### ISSUE TITLE
Status bar color customization

### ISSUE THREAD

**Issue by ilyahal** [mikaoj/BSImagePicker#82]
How to change color the status bar to the white?

I had to make little changes to the source files BSImagePicker. There are other methods?
(In info.plist View controller-based status bar I set YES)

There can be you will make something similar..?

```
let imagePickerViewController = BSImagePickerViewController()
imagePickerViewController.statusBarStyle = .LightContent
```

**Comment by gwigz** [comment]
👍 

I worked around this using the following...

```swift
import BSImagePicker

extension BSImagePickerViewController
{
    public override func preferredStatusBarStyle() -> UIStatusBarStyle
    {
        return .lightContent
    }
}
```
