### ISSUE TITLE
 Count of selections over to the max number of selections when taking new photos.

### ISSUE THREAD

**Issue by DesmondPang** [mikaoj/BSImagePicker#89]
When the selections reach to the max number of selections and then take new photo, it will select the new photo and the count of selections will be over the max number of selections.

Please add  the following code in 

```
if self.photosDataSource?.selections.count < self.settings.maxNumberOfSelections {
                        self.photosDataSource?.selections.append(asset)
 }
```

`func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject])`

to fix the issues.

Thank you.

**Comment by janewu77** [comment]
i updated the code in this way. fyi.

after reaching to the  max number of selections, it cannot open Camera.  FYI

`extension PhotosViewController {
    override func collectionView(_ collectionView: UICollectionView, shouldSelectItemAt indexPath: IndexPath) -> Bool {
        // NOTE: ALWAYS return false. We don't want the collectionView to be the source of thruth regarding selections
        // We can manage it ourself.
        //updated by Jane Wu (move from line 351)
        **guard let photosDataSource = photosDataSource, collectionView.isUserInteractionEnabled else { return false }**
        
        // Camera shouldn't be selected, but pop the UIImagePickerController!
        if let composedDataSource = composedDataSource , composedDataSource.dataSources[indexPath.section].isEqual(cameraDataSource) **&& photosDataSource.selections.count < settings.maxNumberOfSelections**
        {
             //updated by Jane Wu

            let cameraController = UIImagePickerController()
            cameraController.allowsEditing = false
            cameraController.sourceType = .camera
            cameraController.delegate = self
            
            self.present(cameraController, animated: true, completion: nil)
            
            return false
        }
......

`

**Comment by mikaoj** [comment]
I've pulled in a bug fix in master that fixes a max selection bug.
Perhaps it solves this as well, feel free to test it and send in pull requests if it doesn't :)

**Comment by mikaoj** [comment]
Please test version 2.5.1 where above mentioned changes have been made

**Comment by preetam-idyllic** [comment]
in version 2.5.1  this issue seems to be not fixed

**Comment by basilmariano** [comment]
can we also add minNumberOfSelections?
