### ISSUE TITLE
swift 2 BSImagePicker 2.3.0 suddenly uses swift 3 BSGridCollectionViewLayout 1.2.0

### ISSUE THREAD

**Issue by tychop** [mikaoj/BSImagePicker#90]
BSImagePicker 2.3.0 suddenly uses BSGridCollectionViewLayout 1.2.0 instead of BSGridCollectionViewLayout 1.1.1.

This causes major build failures on projects using BSImagePicker 2.3.0 since BSGridCollectionViewLayout 1.2.0 is written for swift 3

Can we get a BSImagePicker 2.3.1 which uses 1.1.1 of BSGridCollectionViewLayout ?

**Comment by mikaoj** [comment]
Thanks. I'll fix it by pushing av version with:
s.dependency 'BSGridCollectionViewLayout', '~> 1.1.1'
soon, hopefully later today.

**Comment by tychop** [comment]
That would be awesome, Thanks in advance !!

**Comment by mikaoj** [comment]
2.3.2 should fix this issue, thanks for reporting it!
