### ISSUE TITLE
Swift compiler error

### ISSUE THREAD

**Issue by zzj19931010** [mikaoj/BSImagePicker#94]
I just upgraded XCode8 and convert my project to swift 2.3. Also I pod install BSImagePicker v2.3 but when I ran my application, there was error message saying "Swift compiler error". I attached one pic to illustrate the problem. Any ideas about solving this problem? Appreciated in advance!
![jietutu](https://cloud.githubusercontent.com/assets/15004416/18700313/2fa01148-7f9c-11e6-8096-a7c07e7006ea.png)

**Comment by zzj19931010** [comment]
Anyone can help please?

**Comment by gwigz** [comment]
#77

**Comment by mikaoj** [comment]
BSImagePicker isn´t Swift 2.3 ready yet. But it will hopefully be soon :)

**Comment by Artfire** [comment]
The same issue :(

**Comment by mikaoj** [comment]
2.4.0 uses Swift 2.3 use that.
I'm working on getting a Swift 3 version out.
