### ISSUE TITLE
initializer for conditional binding must have optional type not uiview

### ISSUE THREAD

**Issue by jigarviprak** [mikaoj/BSImagePicker#95]
func animateTransition(transitionContext: UIViewControllerContextTransitioning) {
        // Get to and from view controller
        if let toViewController = transitionContext.viewControllerForKey(UITransitionContextToViewControllerKey), let fromViewController = transitionContext.viewControllerForKey(UITransitionContextFromViewControllerKey), let sourceImageView = sourceImageView, let destinationImageView = destinationImageView, let containerView = transitionContext.containerView() {....

**Comment by mikaoj** [comment]
Yeah, use 2.4.0 for Swift 2.3.
Or see #77 for Swift 3 support
